// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/ops (interfaces: ObjectAPI,ObjectStore,BackendOps,RuntimeOps,ReplicatorOps,RebalancerOps,OverReplicationOps,ScrubberOps,EncryptionStore,CompressionStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks.go -package=opstest github.com/afreidah/s3-orchestrator/internal/ops ObjectAPI,ObjectStore,BackendOps,RuntimeOps,ReplicatorOps,RebalancerOps,OverReplicationOps,ScrubberOps,EncryptionStore,CompressionStore
//

// Package opstest is a generated GoMock package.
package opstest

import (
	context "context"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	config "github.com/afreidah/s3-orchestrator/internal/config"
	progress "github.com/afreidah/s3-orchestrator/internal/progress"
	object "github.com/afreidah/s3-orchestrator/internal/proxy/object"
	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	worker "github.com/afreidah/s3-orchestrator/internal/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectAPI is a mock of ObjectAPI interface.
type MockObjectAPI struct {
	ctrl     *gomock.Controller
	recorder *MockObjectAPIMockRecorder
	isgomock struct{}
}

// MockObjectAPIMockRecorder is the mock recorder for MockObjectAPI.
type MockObjectAPIMockRecorder struct {
	mock *MockObjectAPI
}

// NewMockObjectAPI creates a new mock instance.
func NewMockObjectAPI(ctrl *gomock.Controller) *MockObjectAPI {
	mock := &MockObjectAPI{ctrl: ctrl}
	mock.recorder = &MockObjectAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectAPI) EXPECT() *MockObjectAPIMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectAPI) DeleteObject(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectAPIMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectAPI)(nil).DeleteObject), ctx, key)
}

// DeleteObjectTags mocks base method.
func (m *MockObjectAPI) DeleteObjectTags(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectTags", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectTags indicates an expected call of DeleteObjectTags.
func (mr *MockObjectAPIMockRecorder) DeleteObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectTags", reflect.TypeOf((*MockObjectAPI)(nil).DeleteObjectTags), ctx, key)
}

// DeleteObjects mocks base method.
func (m *MockObjectAPI) DeleteObjects(ctx context.Context, keys []string) []object.DeleteObjectResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, keys)
	ret0, _ := ret[0].([]object.DeleteObjectResult)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockObjectAPIMockRecorder) DeleteObjects(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockObjectAPI)(nil).DeleteObjects), ctx, keys)
}

// GetObject mocks base method.
func (m *MockObjectAPI) GetObject(ctx context.Context, key, rangeHeader string) (*backend.GetObjectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, key, rangeHeader)
	ret0, _ := ret[0].(*backend.GetObjectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectAPIMockRecorder) GetObject(ctx, key, rangeHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectAPI)(nil).GetObject), ctx, key, rangeHeader)
}

// GetObjectTags mocks base method.
func (m *MockObjectAPI) GetObjectTags(ctx context.Context, key string) ([]core.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectTags", ctx, key)
	ret0, _ := ret[0].([]core.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTags indicates an expected call of GetObjectTags.
func (mr *MockObjectAPIMockRecorder) GetObjectTags(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTags", reflect.TypeOf((*MockObjectAPI)(nil).GetObjectTags), ctx, key)
}

// ListObjects mocks base method.
func (m *MockObjectAPI) ListObjects(ctx context.Context, prefix, delimiter, startAfter string, maxKeys int) (*object.ListObjectsV2Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*object.ListObjectsV2Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectAPIMockRecorder) ListObjects(ctx, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectAPI)(nil).ListObjects), ctx, prefix, delimiter, startAfter, maxKeys)
}

// PutObject mocks base method.
func (m *MockObjectAPI) PutObject(ctx context.Context, req *object.PutObjectRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockObjectAPIMockRecorder) PutObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockObjectAPI)(nil).PutObject), ctx, req)
}

// PutObjectTags mocks base method.
func (m *MockObjectAPI) PutObjectTags(ctx context.Context, key string, tags []core.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObjectTags", ctx, key, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObjectTags indicates an expected call of PutObjectTags.
func (mr *MockObjectAPIMockRecorder) PutObjectTags(ctx, key, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObjectTags", reflect.TypeOf((*MockObjectAPI)(nil).PutObjectTags), ctx, key, tags)
}

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
	isgomock struct{}
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectStore) DeleteObject(ctx context.Context, key string) ([]core.DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectStoreMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectStore)(nil).DeleteObject), ctx, key)
}

// DeleteObjectLocation mocks base method.
func (m *MockObjectStore) DeleteObjectLocation(ctx context.Context, key, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectLocation", ctx, key, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectLocation indicates an expected call of DeleteObjectLocation.
func (mr *MockObjectStoreMockRecorder) DeleteObjectLocation(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectLocation", reflect.TypeOf((*MockObjectStore)(nil).DeleteObjectLocation), ctx, key, backendName)
}

// DeleteObjectsBatch mocks base method.
func (m *MockObjectStore) DeleteObjectsBatch(ctx context.Context, keys []string) (map[string][]core.DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsBatch", ctx, keys)
	ret0, _ := ret[0].(map[string][]core.DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectsBatch indicates an expected call of DeleteObjectsBatch.
func (mr *MockObjectStoreMockRecorder) DeleteObjectsBatch(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsBatch", reflect.TypeOf((*MockObjectStore)(nil).DeleteObjectsBatch), ctx, keys)
}

// GetAllObjectLocations mocks base method.
func (m *MockObjectStore) GetAllObjectLocations(ctx context.Context, key string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectLocations", ctx, key)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjectLocations indicates an expected call of GetAllObjectLocations.
func (mr *MockObjectStoreMockRecorder) GetAllObjectLocations(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectLocations", reflect.TypeOf((*MockObjectStore)(nil).GetAllObjectLocations), ctx, key)
}

// GetObjectBackendsForKeys mocks base method.
func (m *MockObjectStore) GetObjectBackendsForKeys(ctx context.Context, keys []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectBackendsForKeys", ctx, keys)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectBackendsForKeys indicates an expected call of GetObjectBackendsForKeys.
func (mr *MockObjectStoreMockRecorder) GetObjectBackendsForKeys(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectBackendsForKeys", reflect.TypeOf((*MockObjectStore)(nil).GetObjectBackendsForKeys), ctx, keys)
}

// ImportObject mocks base method.
func (m *MockObjectStore) ImportObject(ctx context.Context, key, arg2 string, size int64, unmanaged bool, form *core.StoredForm) (core.ImportOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", ctx, key, arg2, size, unmanaged, form)
	ret0, _ := ret[0].(core.ImportOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockObjectStoreMockRecorder) ImportObject(ctx, key, arg2, size, unmanaged, form any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockObjectStore)(nil).ImportObject), ctx, key, arg2, size, unmanaged, form)
}

// ListObjects mocks base method.
func (m *MockObjectStore) ListObjects(ctx context.Context, prefix, startAfter string, maxKeys int) (*core.ListObjectsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStoreMockRecorder) ListObjects(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectStore)(nil).ListObjects), ctx, prefix, startAfter, maxKeys)
}

// ListObjectsByBackend mocks base method.
func (m *MockObjectStore) ListObjectsByBackend(ctx context.Context, backendName string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackend", ctx, backendName, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackend indicates an expected call of ListObjectsByBackend.
func (mr *MockObjectStoreMockRecorder) ListObjectsByBackend(ctx, backendName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackend", reflect.TypeOf((*MockObjectStore)(nil).ListObjectsByBackend), ctx, backendName, limit)
}

// ListObjectsByBackendKeyAsc mocks base method.
func (m *MockObjectStore) ListObjectsByBackendKeyAsc(ctx context.Context, backendName, afterKey string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackendKeyAsc", ctx, backendName, afterKey, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackendKeyAsc indicates an expected call of ListObjectsByBackendKeyAsc.
func (mr *MockObjectStoreMockRecorder) ListObjectsByBackendKeyAsc(ctx, backendName, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackendKeyAsc", reflect.TypeOf((*MockObjectStore)(nil).ListObjectsByBackendKeyAsc), ctx, backendName, afterKey, limit)
}

// ListObjectsDelimited mocks base method.
func (m *MockObjectStore) ListObjectsDelimited(ctx context.Context, prefix, delimiter, startAfter string, maxKeys int) (*core.ListDelimitedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsDelimited", ctx, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListDelimitedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsDelimited indicates an expected call of ListObjectsDelimited.
func (mr *MockObjectStoreMockRecorder) ListObjectsDelimited(ctx, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsDelimited", reflect.TypeOf((*MockObjectStore)(nil).ListObjectsDelimited), ctx, prefix, delimiter, startAfter, maxKeys)
}

// MoveObjectLocation mocks base method.
func (m *MockObjectStore) MoveObjectLocation(ctx context.Context, key, fromBackend, toBackend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveObjectLocation", ctx, key, fromBackend, toBackend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveObjectLocation indicates an expected call of MoveObjectLocation.
func (mr *MockObjectStoreMockRecorder) MoveObjectLocation(ctx, key, fromBackend, toBackend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObjectLocation", reflect.TypeOf((*MockObjectStore)(nil).MoveObjectLocation), ctx, key, fromBackend, toBackend)
}

// RecordObject mocks base method.
func (m *MockObjectStore) RecordObject(ctx context.Context, req *core.RecordObjectRequest) ([]core.DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObject", ctx, req)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordObject indicates an expected call of RecordObject.
func (mr *MockObjectStoreMockRecorder) RecordObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObject", reflect.TypeOf((*MockObjectStore)(nil).RecordObject), ctx, req)
}

// MockBackendOps is a mock of BackendOps interface.
type MockBackendOps struct {
	ctrl     *gomock.Controller
	recorder *MockBackendOpsMockRecorder
	isgomock struct{}
}

// MockBackendOpsMockRecorder is the mock recorder for MockBackendOps.
type MockBackendOpsMockRecorder struct {
	mock *MockBackendOps
}

// NewMockBackendOps creates a new mock instance.
func NewMockBackendOps(ctrl *gomock.Controller) *MockBackendOps {
	mock := &MockBackendOps{ctrl: ctrl}
	mock.recorder = &MockBackendOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendOps) EXPECT() *MockBackendOpsMockRecorder {
	return m.recorder
}

// AllowUsage mocks base method.
func (m *MockBackendOps) AllowUsage(backendName string, apiCalls, egress, ingress int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowUsage", backendName, apiCalls, egress, ingress)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowUsage indicates an expected call of AllowUsage.
func (mr *MockBackendOpsMockRecorder) AllowUsage(backendName, apiCalls, egress, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowUsage", reflect.TypeOf((*MockBackendOps)(nil).AllowUsage), backendName, apiCalls, egress, ingress)
}

// IntegrityConfig mocks base method.
func (m *MockBackendOps) IntegrityConfig() *config.IntegrityConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntegrityConfig")
	ret0, _ := ret[0].(*config.IntegrityConfig)
	return ret0
}

// IntegrityConfig indicates an expected call of IntegrityConfig.
func (mr *MockBackendOpsMockRecorder) IntegrityConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntegrityConfig", reflect.TypeOf((*MockBackendOps)(nil).IntegrityConfig))
}

// RecordUsage mocks base method.
func (m *MockBackendOps) RecordUsage(backendName string, apiCalls, egress, ingress int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUsage", backendName, apiCalls, egress, ingress)
}

// RecordUsage indicates an expected call of RecordUsage.
func (mr *MockBackendOpsMockRecorder) RecordUsage(backendName, apiCalls, egress, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUsage", reflect.TypeOf((*MockBackendOps)(nil).RecordUsage), backendName, apiCalls, egress, ingress)
}

// MockRuntimeOps is a mock of RuntimeOps interface.
type MockRuntimeOps struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeOpsMockRecorder
	isgomock struct{}
}

// MockRuntimeOpsMockRecorder is the mock recorder for MockRuntimeOps.
type MockRuntimeOpsMockRecorder struct {
	mock *MockRuntimeOps
}

// NewMockRuntimeOps creates a new mock instance.
func NewMockRuntimeOps(ctrl *gomock.Controller) *MockRuntimeOps {
	mock := &MockRuntimeOps{ctrl: ctrl}
	mock.recorder = &MockRuntimeOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeOps) EXPECT() *MockRuntimeOpsMockRecorder {
	return m.recorder
}

// GetBackend mocks base method.
func (m *MockRuntimeOps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockRuntimeOpsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockRuntimeOps)(nil).GetBackend), name)
}

// UpdateQuotaMetrics mocks base method.
func (m *MockRuntimeOps) UpdateQuotaMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotaMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuotaMetrics indicates an expected call of UpdateQuotaMetrics.
func (mr *MockRuntimeOpsMockRecorder) UpdateQuotaMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotaMetrics", reflect.TypeOf((*MockRuntimeOps)(nil).UpdateQuotaMetrics), ctx)
}

// MockReplicatorOps is a mock of ReplicatorOps interface.
type MockReplicatorOps struct {
	ctrl     *gomock.Controller
	recorder *MockReplicatorOpsMockRecorder
	isgomock struct{}
}

// MockReplicatorOpsMockRecorder is the mock recorder for MockReplicatorOps.
type MockReplicatorOpsMockRecorder struct {
	mock *MockReplicatorOps
}

// NewMockReplicatorOps creates a new mock instance.
func NewMockReplicatorOps(ctrl *gomock.Controller) *MockReplicatorOps {
	mock := &MockReplicatorOps{ctrl: ctrl}
	mock.recorder = &MockReplicatorOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplicatorOps) EXPECT() *MockReplicatorOpsMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockReplicatorOps) Config() *config.ReplicationConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.ReplicationConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockReplicatorOpsMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockReplicatorOps)(nil).Config))
}

// Replicate mocks base method.
func (m *MockReplicatorOps) Replicate(ctx context.Context, cfg config.ReplicationConfig, observer progress.Observer) (worker.ReplicationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replicate", ctx, cfg, observer)
	ret0, _ := ret[0].(worker.ReplicationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replicate indicates an expected call of Replicate.
func (mr *MockReplicatorOpsMockRecorder) Replicate(ctx, cfg, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replicate", reflect.TypeOf((*MockReplicatorOps)(nil).Replicate), ctx, cfg, observer)
}

// MockRebalancerOps is a mock of RebalancerOps interface.
type MockRebalancerOps struct {
	ctrl     *gomock.Controller
	recorder *MockRebalancerOpsMockRecorder
	isgomock struct{}
}

// MockRebalancerOpsMockRecorder is the mock recorder for MockRebalancerOps.
type MockRebalancerOpsMockRecorder struct {
	mock *MockRebalancerOps
}

// NewMockRebalancerOps creates a new mock instance.
func NewMockRebalancerOps(ctrl *gomock.Controller) *MockRebalancerOps {
	mock := &MockRebalancerOps{ctrl: ctrl}
	mock.recorder = &MockRebalancerOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRebalancerOps) EXPECT() *MockRebalancerOpsMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockRebalancerOps) Config() *config.RebalanceConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.RebalanceConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockRebalancerOpsMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockRebalancerOps)(nil).Config))
}

// Rebalance mocks base method.
func (m *MockRebalancerOps) Rebalance(ctx context.Context, cfg config.RebalanceConfig, observer progress.Observer) (worker.RebalanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebalance", ctx, cfg, observer)
	ret0, _ := ret[0].(worker.RebalanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rebalance indicates an expected call of Rebalance.
func (mr *MockRebalancerOpsMockRecorder) Rebalance(ctx, cfg, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebalance", reflect.TypeOf((*MockRebalancerOps)(nil).Rebalance), ctx, cfg, observer)
}

// MockOverReplicationOps is a mock of OverReplicationOps interface.
type MockOverReplicationOps struct {
	ctrl     *gomock.Controller
	recorder *MockOverReplicationOpsMockRecorder
	isgomock struct{}
}

// MockOverReplicationOpsMockRecorder is the mock recorder for MockOverReplicationOps.
type MockOverReplicationOpsMockRecorder struct {
	mock *MockOverReplicationOps
}

// NewMockOverReplicationOps creates a new mock instance.
func NewMockOverReplicationOps(ctrl *gomock.Controller) *MockOverReplicationOps {
	mock := &MockOverReplicationOps{ctrl: ctrl}
	mock.recorder = &MockOverReplicationOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOverReplicationOps) EXPECT() *MockOverReplicationOpsMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockOverReplicationOps) Clean(ctx context.Context, cfg config.ReplicationConfig, observer progress.Observer) (worker.OverReplicationSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, cfg, observer)
	ret0, _ := ret[0].(worker.OverReplicationSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockOverReplicationOpsMockRecorder) Clean(ctx, cfg, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockOverReplicationOps)(nil).Clean), ctx, cfg, observer)
}

// Config mocks base method.
func (m *MockOverReplicationOps) Config() *config.ReplicationConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.ReplicationConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockOverReplicationOpsMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockOverReplicationOps)(nil).Config))
}

// CountPending mocks base method.
func (m *MockOverReplicationOps) CountPending(ctx context.Context, factor int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPending", ctx, factor)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPending indicates an expected call of CountPending.
func (mr *MockOverReplicationOpsMockRecorder) CountPending(ctx, factor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPending", reflect.TypeOf((*MockOverReplicationOps)(nil).CountPending), ctx, factor)
}

// MockScrubberOps is a mock of ScrubberOps interface.
type MockScrubberOps struct {
	ctrl     *gomock.Controller
	recorder *MockScrubberOpsMockRecorder
	isgomock struct{}
}

// MockScrubberOpsMockRecorder is the mock recorder for MockScrubberOps.
type MockScrubberOpsMockRecorder struct {
	mock *MockScrubberOps
}

// NewMockScrubberOps creates a new mock instance.
func NewMockScrubberOps(ctrl *gomock.Controller) *MockScrubberOps {
	mock := &MockScrubberOps{ctrl: ctrl}
	mock.recorder = &MockScrubberOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrubberOps) EXPECT() *MockScrubberOpsMockRecorder {
	return m.recorder
}

// Backfill mocks base method.
func (m *MockScrubberOps) Backfill(ctx context.Context, batchSize, offset int, observer progress.Observer) (worker.WorkSummary, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backfill", ctx, batchSize, offset, observer)
	ret0, _ := ret[0].(worker.WorkSummary)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Backfill indicates an expected call of Backfill.
func (mr *MockScrubberOpsMockRecorder) Backfill(ctx, batchSize, offset, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backfill", reflect.TypeOf((*MockScrubberOps)(nil).Backfill), ctx, batchSize, offset, observer)
}

// Scrub mocks base method.
func (m *MockScrubberOps) Scrub(ctx context.Context, batchSize int, observer progress.Observer) worker.WorkSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrub", ctx, batchSize, observer)
	ret0, _ := ret[0].(worker.WorkSummary)
	return ret0
}

// Scrub indicates an expected call of Scrub.
func (mr *MockScrubberOpsMockRecorder) Scrub(ctx, batchSize, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrub", reflect.TypeOf((*MockScrubberOps)(nil).Scrub), ctx, batchSize, observer)
}

// ScrubKey mocks base method.
func (m *MockScrubberOps) ScrubKey(ctx context.Context, key string) ([]worker.CopyVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrubKey", ctx, key)
	ret0, _ := ret[0].([]worker.CopyVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScrubKey indicates an expected call of ScrubKey.
func (mr *MockScrubberOpsMockRecorder) ScrubKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrubKey", reflect.TypeOf((*MockScrubberOps)(nil).ScrubKey), ctx, key)
}

// MockEncryptionStore is a mock of EncryptionStore interface.
type MockEncryptionStore struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionStoreMockRecorder
	isgomock struct{}
}

// MockEncryptionStoreMockRecorder is the mock recorder for MockEncryptionStore.
type MockEncryptionStoreMockRecorder struct {
	mock *MockEncryptionStore
}

// NewMockEncryptionStore creates a new mock instance.
func NewMockEncryptionStore(ctrl *gomock.Controller) *MockEncryptionStore {
	mock := &MockEncryptionStore{ctrl: ctrl}
	mock.recorder = &MockEncryptionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionStore) EXPECT() *MockEncryptionStoreMockRecorder {
	return m.recorder
}

// CountUnencryptedLocations mocks base method.
func (m *MockEncryptionStore) CountUnencryptedLocations(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnencryptedLocations", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnencryptedLocations indicates an expected call of CountUnencryptedLocations.
func (mr *MockEncryptionStoreMockRecorder) CountUnencryptedLocations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnencryptedLocations", reflect.TypeOf((*MockEncryptionStore)(nil).CountUnencryptedLocations), ctx)
}

// ListAllEncryptedLocations mocks base method.
func (m *MockEncryptionStore) ListAllEncryptedLocations(ctx context.Context, limit int, after core.Cursor) ([]core.DecryptableLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllEncryptedLocations", ctx, limit, after)
	ret0, _ := ret[0].([]core.DecryptableLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllEncryptedLocations indicates an expected call of ListAllEncryptedLocations.
func (mr *MockEncryptionStoreMockRecorder) ListAllEncryptedLocations(ctx, limit, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllEncryptedLocations", reflect.TypeOf((*MockEncryptionStore)(nil).ListAllEncryptedLocations), ctx, limit, after)
}

// ListEncryptedLocations mocks base method.
func (m *MockEncryptionStore) ListEncryptedLocations(ctx context.Context, keyID string, limit, offset int) ([]core.EncryptedLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEncryptedLocations", ctx, keyID, limit, offset)
	ret0, _ := ret[0].([]core.EncryptedLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEncryptedLocations indicates an expected call of ListEncryptedLocations.
func (mr *MockEncryptionStoreMockRecorder) ListEncryptedLocations(ctx, keyID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEncryptedLocations", reflect.TypeOf((*MockEncryptionStore)(nil).ListEncryptedLocations), ctx, keyID, limit, offset)
}

// ListUnencryptedLocations mocks base method.
func (m *MockEncryptionStore) ListUnencryptedLocations(ctx context.Context, limit int, after core.Cursor) ([]core.UnencryptedLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnencryptedLocations", ctx, limit, after)
	ret0, _ := ret[0].([]core.UnencryptedLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnencryptedLocations indicates an expected call of ListUnencryptedLocations.
func (mr *MockEncryptionStoreMockRecorder) ListUnencryptedLocations(ctx, limit, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnencryptedLocations", reflect.TypeOf((*MockEncryptionStore)(nil).ListUnencryptedLocations), ctx, limit, after)
}

// MarkObjectDecrypted mocks base method.
func (m *MockEncryptionStore) MarkObjectDecrypted(ctx context.Context, objectKey, backendName string, plaintextSize int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectDecrypted", ctx, objectKey, backendName, plaintextSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectDecrypted indicates an expected call of MarkObjectDecrypted.
func (mr *MockEncryptionStoreMockRecorder) MarkObjectDecrypted(ctx, objectKey, backendName, plaintextSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectDecrypted", reflect.TypeOf((*MockEncryptionStore)(nil).MarkObjectDecrypted), ctx, objectKey, backendName, plaintextSize)
}

// MarkObjectEncrypted mocks base method.
func (m *MockEncryptionStore) MarkObjectEncrypted(ctx context.Context, objectKey, backendName string, encryptionKey []byte, keyID string, plaintextSize, ciphertextSize int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectEncrypted", ctx, objectKey, backendName, encryptionKey, keyID, plaintextSize, ciphertextSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectEncrypted indicates an expected call of MarkObjectEncrypted.
func (mr *MockEncryptionStoreMockRecorder) MarkObjectEncrypted(ctx, objectKey, backendName, encryptionKey, keyID, plaintextSize, ciphertextSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectEncrypted", reflect.TypeOf((*MockEncryptionStore)(nil).MarkObjectEncrypted), ctx, objectKey, backendName, encryptionKey, keyID, plaintextSize, ciphertextSize)
}

// UpdateEncryptionKey mocks base method.
func (m *MockEncryptionStore) UpdateEncryptionKey(ctx context.Context, objectKey, backendName string, newEncryptionKey []byte, newKeyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncryptionKey", ctx, objectKey, backendName, newEncryptionKey, newKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEncryptionKey indicates an expected call of UpdateEncryptionKey.
func (mr *MockEncryptionStoreMockRecorder) UpdateEncryptionKey(ctx, objectKey, backendName, newEncryptionKey, newKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncryptionKey", reflect.TypeOf((*MockEncryptionStore)(nil).UpdateEncryptionKey), ctx, objectKey, backendName, newEncryptionKey, newKeyID)
}

// MockCompressionStore is a mock of CompressionStore interface.
type MockCompressionStore struct {
	ctrl     *gomock.Controller
	recorder *MockCompressionStoreMockRecorder
	isgomock struct{}
}

// MockCompressionStoreMockRecorder is the mock recorder for MockCompressionStore.
type MockCompressionStoreMockRecorder struct {
	mock *MockCompressionStore
}

// NewMockCompressionStore creates a new mock instance.
func NewMockCompressionStore(ctrl *gomock.Controller) *MockCompressionStore {
	mock := &MockCompressionStore{ctrl: ctrl}
	mock.recorder = &MockCompressionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompressionStore) EXPECT() *MockCompressionStoreMockRecorder {
	return m.recorder
}

// ListCompressedLocations mocks base method.
func (m *MockCompressionStore) ListCompressedLocations(ctx context.Context, limit int, after core.Cursor) ([]core.RewritableLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompressedLocations", ctx, limit, after)
	ret0, _ := ret[0].([]core.RewritableLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompressedLocations indicates an expected call of ListCompressedLocations.
func (mr *MockCompressionStoreMockRecorder) ListCompressedLocations(ctx, limit, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompressedLocations", reflect.TypeOf((*MockCompressionStore)(nil).ListCompressedLocations), ctx, limit, after)
}

// ListUncompressedLocations mocks base method.
func (m *MockCompressionStore) ListUncompressedLocations(ctx context.Context, limit int, after core.Cursor, t core.CompressionThresholds) ([]core.RewritableLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUncompressedLocations", ctx, limit, after, t)
	ret0, _ := ret[0].([]core.RewritableLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUncompressedLocations indicates an expected call of ListUncompressedLocations.
func (mr *MockCompressionStoreMockRecorder) ListUncompressedLocations(ctx, limit, after, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUncompressedLocations", reflect.TypeOf((*MockCompressionStore)(nil).ListUncompressedLocations), ctx, limit, after, t)
}

// MarkObjectCompressed mocks base method.
func (m *MockCompressionStore) MarkObjectCompressed(ctx context.Context, u *core.CompressedUpdate, previousSize int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkObjectCompressed", ctx, u, previousSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkObjectCompressed indicates an expected call of MarkObjectCompressed.
func (mr *MockCompressionStoreMockRecorder) MarkObjectCompressed(ctx, u, previousSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkObjectCompressed", reflect.TypeOf((*MockCompressionStore)(nil).MarkObjectCompressed), ctx, u, previousSize)
}

// RecordCompressionProbe mocks base method.
func (m *MockCompressionStore) RecordCompressionProbe(ctx context.Context, probe *core.CompressionProbe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCompressionProbe", ctx, probe)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordCompressionProbe indicates an expected call of RecordCompressionProbe.
func (mr *MockCompressionStoreMockRecorder) RecordCompressionProbe(ctx, probe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCompressionProbe", reflect.TypeOf((*MockCompressionStore)(nil).RecordCompressionProbe), ctx, probe)
}
