# -------------------------------------------------------------------------------
# golangci-lint Configuration
#
# Author: Alex Freidah
#
# Linter settings for static analysis. Enables gocritic (diagnostic + performance
# tags) and misspell. Excludes generated sqlc code from analysis.
# -------------------------------------------------------------------------------

version: "2"
linters:
  enable:
    - gocritic
    - misspell
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
      enabled-tags:
        - diagnostic
        - performance
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/storage/sqlc
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
