// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/store/core (interfaces: ObjectStore,QuotaStore,CleanupStore,ExpiredObjectsLister,BackendLifecycleStore,DashboardStore,LifecycleAdmin)
//
// Generated by this command:
//
//	mockgen -destination=role_mocks.go -package=storetest github.com/afreidah/s3-orchestrator/internal/store/core ObjectStore,QuotaStore,CleanupStore,ExpiredObjectsLister,BackendLifecycleStore,DashboardStore,LifecycleAdmin
//

// Package storetest is a generated GoMock package.
package storetest

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/afreidah/s3-orchestrator/internal/config"
	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
	isgomock struct{}
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectStore) DeleteObject(ctx context.Context, key string) ([]core.DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectStoreMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectStore)(nil).DeleteObject), ctx, key)
}

// DeleteObjectLocation mocks base method.
func (m *MockObjectStore) DeleteObjectLocation(ctx context.Context, key, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectLocation", ctx, key, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectLocation indicates an expected call of DeleteObjectLocation.
func (mr *MockObjectStoreMockRecorder) DeleteObjectLocation(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectLocation", reflect.TypeOf((*MockObjectStore)(nil).DeleteObjectLocation), ctx, key, backendName)
}

// DeleteObjectsBatch mocks base method.
func (m *MockObjectStore) DeleteObjectsBatch(ctx context.Context, keys []string) (map[string][]core.DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectsBatch", ctx, keys)
	ret0, _ := ret[0].(map[string][]core.DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectsBatch indicates an expected call of DeleteObjectsBatch.
func (mr *MockObjectStoreMockRecorder) DeleteObjectsBatch(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectsBatch", reflect.TypeOf((*MockObjectStore)(nil).DeleteObjectsBatch), ctx, keys)
}

// GetAllObjectLocations mocks base method.
func (m *MockObjectStore) GetAllObjectLocations(ctx context.Context, key string) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectLocations", ctx, key)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjectLocations indicates an expected call of GetAllObjectLocations.
func (mr *MockObjectStoreMockRecorder) GetAllObjectLocations(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectLocations", reflect.TypeOf((*MockObjectStore)(nil).GetAllObjectLocations), ctx, key)
}

// GetObjectBackendsForKeys mocks base method.
func (m *MockObjectStore) GetObjectBackendsForKeys(ctx context.Context, keys []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectBackendsForKeys", ctx, keys)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectBackendsForKeys indicates an expected call of GetObjectBackendsForKeys.
func (mr *MockObjectStoreMockRecorder) GetObjectBackendsForKeys(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectBackendsForKeys", reflect.TypeOf((*MockObjectStore)(nil).GetObjectBackendsForKeys), ctx, keys)
}

// ImportObject mocks base method.
func (m *MockObjectStore) ImportObject(ctx context.Context, key, backend string, size int64, unmanaged bool, form *core.StoredForm) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", ctx, key, backend, size, unmanaged, form)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockObjectStoreMockRecorder) ImportObject(ctx, key, backend, size, unmanaged, form any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockObjectStore)(nil).ImportObject), ctx, key, backend, size, unmanaged, form)
}

// ListObjects mocks base method.
func (m *MockObjectStore) ListObjects(ctx context.Context, prefix, startAfter string, maxKeys int) (*core.ListObjectsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockObjectStoreMockRecorder) ListObjects(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockObjectStore)(nil).ListObjects), ctx, prefix, startAfter, maxKeys)
}

// ListObjectsByBackend mocks base method.
func (m *MockObjectStore) ListObjectsByBackend(ctx context.Context, backendName string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackend", ctx, backendName, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackend indicates an expected call of ListObjectsByBackend.
func (mr *MockObjectStoreMockRecorder) ListObjectsByBackend(ctx, backendName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackend", reflect.TypeOf((*MockObjectStore)(nil).ListObjectsByBackend), ctx, backendName, limit)
}

// ListObjectsByBackendKeyAsc mocks base method.
func (m *MockObjectStore) ListObjectsByBackendKeyAsc(ctx context.Context, backendName, afterKey string, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackendKeyAsc", ctx, backendName, afterKey, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackendKeyAsc indicates an expected call of ListObjectsByBackendKeyAsc.
func (mr *MockObjectStoreMockRecorder) ListObjectsByBackendKeyAsc(ctx, backendName, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackendKeyAsc", reflect.TypeOf((*MockObjectStore)(nil).ListObjectsByBackendKeyAsc), ctx, backendName, afterKey, limit)
}

// ListObjectsDelimited mocks base method.
func (m *MockObjectStore) ListObjectsDelimited(ctx context.Context, prefix, delimiter, startAfter string, maxKeys int) (*core.ListDelimitedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsDelimited", ctx, prefix, delimiter, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.ListDelimitedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsDelimited indicates an expected call of ListObjectsDelimited.
func (mr *MockObjectStoreMockRecorder) ListObjectsDelimited(ctx, prefix, delimiter, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsDelimited", reflect.TypeOf((*MockObjectStore)(nil).ListObjectsDelimited), ctx, prefix, delimiter, startAfter, maxKeys)
}

// MoveObjectLocation mocks base method.
func (m *MockObjectStore) MoveObjectLocation(ctx context.Context, key, fromBackend, toBackend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveObjectLocation", ctx, key, fromBackend, toBackend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveObjectLocation indicates an expected call of MoveObjectLocation.
func (mr *MockObjectStoreMockRecorder) MoveObjectLocation(ctx, key, fromBackend, toBackend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObjectLocation", reflect.TypeOf((*MockObjectStore)(nil).MoveObjectLocation), ctx, key, fromBackend, toBackend)
}

// RecordObject mocks base method.
func (m *MockObjectStore) RecordObject(ctx context.Context, req *core.RecordObjectRequest) ([]core.DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObject", ctx, req)
	ret0, _ := ret[0].([]core.DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordObject indicates an expected call of RecordObject.
func (mr *MockObjectStoreMockRecorder) RecordObject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObject", reflect.TypeOf((*MockObjectStore)(nil).RecordObject), ctx, req)
}

// MockQuotaStore is a mock of QuotaStore interface.
type MockQuotaStore struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaStoreMockRecorder
	isgomock struct{}
}

// MockQuotaStoreMockRecorder is the mock recorder for MockQuotaStore.
type MockQuotaStoreMockRecorder struct {
	mock *MockQuotaStore
}

// NewMockQuotaStore creates a new mock instance.
func NewMockQuotaStore(ctrl *gomock.Controller) *MockQuotaStore {
	mock := &MockQuotaStore{ctrl: ctrl}
	mock.recorder = &MockQuotaStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaStore) EXPECT() *MockQuotaStoreMockRecorder {
	return m.recorder
}

// GetBackendWithSpace mocks base method.
func (m *MockQuotaStore) GetBackendWithSpace(ctx context.Context, size int64, backendOrder []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackendWithSpace", ctx, size, backendOrder)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackendWithSpace indicates an expected call of GetBackendWithSpace.
func (mr *MockQuotaStoreMockRecorder) GetBackendWithSpace(ctx, size, backendOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackendWithSpace", reflect.TypeOf((*MockQuotaStore)(nil).GetBackendWithSpace), ctx, size, backendOrder)
}

// GetLeastUtilizedBackend mocks base method.
func (m *MockQuotaStore) GetLeastUtilizedBackend(ctx context.Context, size int64, eligible []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeastUtilizedBackend", ctx, size, eligible)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeastUtilizedBackend indicates an expected call of GetLeastUtilizedBackend.
func (mr *MockQuotaStoreMockRecorder) GetLeastUtilizedBackend(ctx, size, eligible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeastUtilizedBackend", reflect.TypeOf((*MockQuotaStore)(nil).GetLeastUtilizedBackend), ctx, size, eligible)
}

// GetQuotaStats mocks base method.
func (m *MockQuotaStore) GetQuotaStats(ctx context.Context) (map[string]core.QuotaStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaStats", ctx)
	ret0, _ := ret[0].(map[string]core.QuotaStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaStats indicates an expected call of GetQuotaStats.
func (mr *MockQuotaStoreMockRecorder) GetQuotaStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaStats", reflect.TypeOf((*MockQuotaStore)(nil).GetQuotaStats), ctx)
}

// ReconcileUsage mocks base method.
func (m *MockQuotaStore) ReconcileUsage(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileUsage", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileUsage indicates an expected call of ReconcileUsage.
func (mr *MockQuotaStoreMockRecorder) ReconcileUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileUsage", reflect.TypeOf((*MockQuotaStore)(nil).ReconcileUsage), ctx)
}

// MockCleanupStore is a mock of CleanupStore interface.
type MockCleanupStore struct {
	ctrl     *gomock.Controller
	recorder *MockCleanupStoreMockRecorder
	isgomock struct{}
}

// MockCleanupStoreMockRecorder is the mock recorder for MockCleanupStore.
type MockCleanupStoreMockRecorder struct {
	mock *MockCleanupStore
}

// NewMockCleanupStore creates a new mock instance.
func NewMockCleanupStore(ctrl *gomock.Controller) *MockCleanupStore {
	mock := &MockCleanupStore{ctrl: ctrl}
	mock.recorder = &MockCleanupStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleanupStore) EXPECT() *MockCleanupStoreMockRecorder {
	return m.recorder
}

// ClaimPendingCleanups mocks base method.
func (m *MockCleanupStore) ClaimPendingCleanups(ctx context.Context, limit int, instanceID string, graceCutoff time.Time) ([]core.CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingCleanups", ctx, limit, instanceID, graceCutoff)
	ret0, _ := ret[0].([]core.CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingCleanups indicates an expected call of ClaimPendingCleanups.
func (mr *MockCleanupStoreMockRecorder) ClaimPendingCleanups(ctx, limit, instanceID, graceCutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingCleanups", reflect.TypeOf((*MockCleanupStore)(nil).ClaimPendingCleanups), ctx, limit, instanceID, graceCutoff)
}

// CleanupDLQDepth mocks base method.
func (m *MockCleanupStore) CleanupDLQDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupDLQDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupDLQDepth indicates an expected call of CleanupDLQDepth.
func (mr *MockCleanupStoreMockRecorder) CleanupDLQDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDLQDepth", reflect.TypeOf((*MockCleanupStore)(nil).CleanupDLQDepth), ctx)
}

// CleanupQueueDepth mocks base method.
func (m *MockCleanupStore) CleanupQueueDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupQueueDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupQueueDepth indicates an expected call of CleanupQueueDepth.
func (mr *MockCleanupStoreMockRecorder) CleanupQueueDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupQueueDepth", reflect.TypeOf((*MockCleanupStore)(nil).CleanupQueueDepth), ctx)
}

// CompleteCleanupItem mocks base method.
func (m *MockCleanupStore) CompleteCleanupItem(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCleanupItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteCleanupItem indicates an expected call of CompleteCleanupItem.
func (mr *MockCleanupStoreMockRecorder) CompleteCleanupItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCleanupItem", reflect.TypeOf((*MockCleanupStore)(nil).CompleteCleanupItem), ctx, id)
}

// DecrementOrphanBytes mocks base method.
func (m *MockCleanupStore) DecrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOrphanBytes indicates an expected call of DecrementOrphanBytes.
func (mr *MockCleanupStoreMockRecorder) DecrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOrphanBytes", reflect.TypeOf((*MockCleanupStore)(nil).DecrementOrphanBytes), ctx, backendName, amount)
}

// EnqueueCleanup mocks base method.
func (m *MockCleanupStore) EnqueueCleanup(ctx context.Context, backendName, objectKey, reason string, sizeBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueCleanup", ctx, backendName, objectKey, reason, sizeBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueCleanup indicates an expected call of EnqueueCleanup.
func (mr *MockCleanupStoreMockRecorder) EnqueueCleanup(ctx, backendName, objectKey, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueCleanup", reflect.TypeOf((*MockCleanupStore)(nil).EnqueueCleanup), ctx, backendName, objectKey, reason, sizeBytes)
}

// GetPendingCleanups mocks base method.
func (m *MockCleanupStore) GetPendingCleanups(ctx context.Context, limit int) ([]core.CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingCleanups", ctx, limit)
	ret0, _ := ret[0].([]core.CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingCleanups indicates an expected call of GetPendingCleanups.
func (mr *MockCleanupStoreMockRecorder) GetPendingCleanups(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingCleanups", reflect.TypeOf((*MockCleanupStore)(nil).GetPendingCleanups), ctx, limit)
}

// IncrementOrphanBytes mocks base method.
func (m *MockCleanupStore) IncrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOrphanBytes indicates an expected call of IncrementOrphanBytes.
func (mr *MockCleanupStoreMockRecorder) IncrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOrphanBytes", reflect.TypeOf((*MockCleanupStore)(nil).IncrementOrphanBytes), ctx, backendName, amount)
}

// ListCleanupDLQ mocks base method.
func (m *MockCleanupStore) ListCleanupDLQ(ctx context.Context, backend string, limit int) ([]core.CleanupDLQItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCleanupDLQ", ctx, backend, limit)
	ret0, _ := ret[0].([]core.CleanupDLQItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCleanupDLQ indicates an expected call of ListCleanupDLQ.
func (mr *MockCleanupStoreMockRecorder) ListCleanupDLQ(ctx, backend, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCleanupDLQ", reflect.TypeOf((*MockCleanupStore)(nil).ListCleanupDLQ), ctx, backend, limit)
}

// MoveCleanupToDLQ mocks base method.
func (m *MockCleanupStore) MoveCleanupToDLQ(ctx context.Context, id int64, lastError string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveCleanupToDLQ", ctx, id, lastError)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveCleanupToDLQ indicates an expected call of MoveCleanupToDLQ.
func (mr *MockCleanupStoreMockRecorder) MoveCleanupToDLQ(ctx, id, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCleanupToDLQ", reflect.TypeOf((*MockCleanupStore)(nil).MoveCleanupToDLQ), ctx, id, lastError)
}

// RequeueCleanupDLQ mocks base method.
func (m *MockCleanupStore) RequeueCleanupDLQ(ctx context.Context, backend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueCleanupDLQ", ctx, backend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequeueCleanupDLQ indicates an expected call of RequeueCleanupDLQ.
func (mr *MockCleanupStoreMockRecorder) RequeueCleanupDLQ(ctx, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueCleanupDLQ", reflect.TypeOf((*MockCleanupStore)(nil).RequeueCleanupDLQ), ctx, backend)
}

// RetryCleanupItem mocks base method.
func (m *MockCleanupStore) RetryCleanupItem(ctx context.Context, id int64, backoff time.Duration, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryCleanupItem", ctx, id, backoff, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryCleanupItem indicates an expected call of RetryCleanupItem.
func (mr *MockCleanupStoreMockRecorder) RetryCleanupItem(ctx, id, backoff, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryCleanupItem", reflect.TypeOf((*MockCleanupStore)(nil).RetryCleanupItem), ctx, id, backoff, lastError)
}

// SweepStaleCleanupQueueRows mocks base method.
func (m *MockCleanupStore) SweepStaleCleanupQueueRows(ctx context.Context, key, backend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepStaleCleanupQueueRows", ctx, key, backend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepStaleCleanupQueueRows indicates an expected call of SweepStaleCleanupQueueRows.
func (mr *MockCleanupStoreMockRecorder) SweepStaleCleanupQueueRows(ctx, key, backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepStaleCleanupQueueRows", reflect.TypeOf((*MockCleanupStore)(nil).SweepStaleCleanupQueueRows), ctx, key, backend)
}

// MockExpiredObjectsLister is a mock of ExpiredObjectsLister interface.
type MockExpiredObjectsLister struct {
	ctrl     *gomock.Controller
	recorder *MockExpiredObjectsListerMockRecorder
	isgomock struct{}
}

// MockExpiredObjectsListerMockRecorder is the mock recorder for MockExpiredObjectsLister.
type MockExpiredObjectsListerMockRecorder struct {
	mock *MockExpiredObjectsLister
}

// NewMockExpiredObjectsLister creates a new mock instance.
func NewMockExpiredObjectsLister(ctrl *gomock.Controller) *MockExpiredObjectsLister {
	mock := &MockExpiredObjectsLister{ctrl: ctrl}
	mock.recorder = &MockExpiredObjectsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpiredObjectsLister) EXPECT() *MockExpiredObjectsListerMockRecorder {
	return m.recorder
}

// ListExpiredObjects mocks base method.
func (m *MockExpiredObjectsLister) ListExpiredObjects(ctx context.Context, prefix string, cutoff time.Time, limit int) ([]core.ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredObjects", ctx, prefix, cutoff, limit)
	ret0, _ := ret[0].([]core.ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredObjects indicates an expected call of ListExpiredObjects.
func (mr *MockExpiredObjectsListerMockRecorder) ListExpiredObjects(ctx, prefix, cutoff, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredObjects", reflect.TypeOf((*MockExpiredObjectsLister)(nil).ListExpiredObjects), ctx, prefix, cutoff, limit)
}

// MockBackendLifecycleStore is a mock of BackendLifecycleStore interface.
type MockBackendLifecycleStore struct {
	ctrl     *gomock.Controller
	recorder *MockBackendLifecycleStoreMockRecorder
	isgomock struct{}
}

// MockBackendLifecycleStoreMockRecorder is the mock recorder for MockBackendLifecycleStore.
type MockBackendLifecycleStoreMockRecorder struct {
	mock *MockBackendLifecycleStore
}

// NewMockBackendLifecycleStore creates a new mock instance.
func NewMockBackendLifecycleStore(ctrl *gomock.Controller) *MockBackendLifecycleStore {
	mock := &MockBackendLifecycleStore{ctrl: ctrl}
	mock.recorder = &MockBackendLifecycleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendLifecycleStore) EXPECT() *MockBackendLifecycleStoreMockRecorder {
	return m.recorder
}

// BackendObjectStats mocks base method.
func (m *MockBackendLifecycleStore) BackendObjectStats(ctx context.Context, backendName string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendObjectStats", ctx, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BackendObjectStats indicates an expected call of BackendObjectStats.
func (mr *MockBackendLifecycleStoreMockRecorder) BackendObjectStats(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendObjectStats", reflect.TypeOf((*MockBackendLifecycleStore)(nil).BackendObjectStats), ctx, backendName)
}

// DeleteBackendData mocks base method.
func (m *MockBackendLifecycleStore) DeleteBackendData(ctx context.Context, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackendData", ctx, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackendData indicates an expected call of DeleteBackendData.
func (mr *MockBackendLifecycleStoreMockRecorder) DeleteBackendData(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackendData", reflect.TypeOf((*MockBackendLifecycleStore)(nil).DeleteBackendData), ctx, backendName)
}

// MockDashboardStore is a mock of DashboardStore interface.
type MockDashboardStore struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardStoreMockRecorder
	isgomock struct{}
}

// MockDashboardStoreMockRecorder is the mock recorder for MockDashboardStore.
type MockDashboardStoreMockRecorder struct {
	mock *MockDashboardStore
}

// NewMockDashboardStore creates a new mock instance.
func NewMockDashboardStore(ctrl *gomock.Controller) *MockDashboardStore {
	mock := &MockDashboardStore{ctrl: ctrl}
	mock.recorder = &MockDashboardStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardStore) EXPECT() *MockDashboardStoreMockRecorder {
	return m.recorder
}

// CompressionStats mocks base method.
func (m *MockDashboardStore) CompressionStats(ctx context.Context) (map[string]core.CompressionStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressionStats", ctx)
	ret0, _ := ret[0].(map[string]core.CompressionStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompressionStats indicates an expected call of CompressionStats.
func (mr *MockDashboardStoreMockRecorder) CompressionStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressionStats", reflect.TypeOf((*MockDashboardStore)(nil).CompressionStats), ctx)
}

// CountUnencryptedLocations mocks base method.
func (m *MockDashboardStore) CountUnencryptedLocations(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnencryptedLocations", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnencryptedLocations indicates an expected call of CountUnencryptedLocations.
func (mr *MockDashboardStoreMockRecorder) CountUnencryptedLocations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnencryptedLocations", reflect.TypeOf((*MockDashboardStore)(nil).CountUnencryptedLocations), ctx)
}

// GetActiveMultipartCounts mocks base method.
func (m *MockDashboardStore) GetActiveMultipartCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMultipartCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMultipartCounts indicates an expected call of GetActiveMultipartCounts.
func (mr *MockDashboardStoreMockRecorder) GetActiveMultipartCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMultipartCounts", reflect.TypeOf((*MockDashboardStore)(nil).GetActiveMultipartCounts), ctx)
}

// GetObjectCounts mocks base method.
func (m *MockDashboardStore) GetObjectCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectCounts indicates an expected call of GetObjectCounts.
func (mr *MockDashboardStoreMockRecorder) GetObjectCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectCounts", reflect.TypeOf((*MockDashboardStore)(nil).GetObjectCounts), ctx)
}

// GetQuotaStats mocks base method.
func (m *MockDashboardStore) GetQuotaStats(ctx context.Context) (map[string]core.QuotaStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaStats", ctx)
	ret0, _ := ret[0].(map[string]core.QuotaStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaStats indicates an expected call of GetQuotaStats.
func (mr *MockDashboardStoreMockRecorder) GetQuotaStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaStats", reflect.TypeOf((*MockDashboardStore)(nil).GetQuotaStats), ctx)
}

// GetUnverifiedObjectCounts mocks base method.
func (m *MockDashboardStore) GetUnverifiedObjectCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnverifiedObjectCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnverifiedObjectCounts indicates an expected call of GetUnverifiedObjectCounts.
func (mr *MockDashboardStoreMockRecorder) GetUnverifiedObjectCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnverifiedObjectCounts", reflect.TypeOf((*MockDashboardStore)(nil).GetUnverifiedObjectCounts), ctx)
}

// GetUsageForPeriod mocks base method.
func (m *MockDashboardStore) GetUsageForPeriod(ctx context.Context, period string) (map[string]core.UsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsageForPeriod", ctx, period)
	ret0, _ := ret[0].(map[string]core.UsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsageForPeriod indicates an expected call of GetUsageForPeriod.
func (mr *MockDashboardStoreMockRecorder) GetUsageForPeriod(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsageForPeriod", reflect.TypeOf((*MockDashboardStore)(nil).GetUsageForPeriod), ctx, period)
}

// ListDirectoryChildren mocks base method.
func (m *MockDashboardStore) ListDirectoryChildren(ctx context.Context, prefix, startAfter string, maxKeys int) (*core.DirectoryListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDirectoryChildren", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*core.DirectoryListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDirectoryChildren indicates an expected call of ListDirectoryChildren.
func (mr *MockDashboardStoreMockRecorder) ListDirectoryChildren(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDirectoryChildren", reflect.TypeOf((*MockDashboardStore)(nil).ListDirectoryChildren), ctx, prefix, startAfter, maxKeys)
}

// OldestUnverifiedAge mocks base method.
func (m *MockDashboardStore) OldestUnverifiedAge(ctx context.Context) (time.Duration, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OldestUnverifiedAge", ctx)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OldestUnverifiedAge indicates an expected call of OldestUnverifiedAge.
func (mr *MockDashboardStoreMockRecorder) OldestUnverifiedAge(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OldestUnverifiedAge", reflect.TypeOf((*MockDashboardStore)(nil).OldestUnverifiedAge), ctx)
}

// MockLifecycleAdmin is a mock of LifecycleAdmin interface.
type MockLifecycleAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleAdminMockRecorder
	isgomock struct{}
}

// MockLifecycleAdminMockRecorder is the mock recorder for MockLifecycleAdmin.
type MockLifecycleAdminMockRecorder struct {
	mock *MockLifecycleAdmin
}

// NewMockLifecycleAdmin creates a new mock instance.
func NewMockLifecycleAdmin(ctrl *gomock.Controller) *MockLifecycleAdmin {
	mock := &MockLifecycleAdmin{ctrl: ctrl}
	mock.recorder = &MockLifecycleAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycleAdmin) EXPECT() *MockLifecycleAdminMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLifecycleAdmin) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockLifecycleAdminMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLifecycleAdmin)(nil).Close))
}

// RunMigrations mocks base method.
func (m *MockLifecycleAdmin) RunMigrations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrations indicates an expected call of RunMigrations.
func (mr *MockLifecycleAdminMockRecorder) RunMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrations", reflect.TypeOf((*MockLifecycleAdmin)(nil).RunMigrations), ctx)
}

// SyncQuotaLimits mocks base method.
func (m *MockLifecycleAdmin) SyncQuotaLimits(ctx context.Context, backends []config.BackendConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncQuotaLimits", ctx, backends)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncQuotaLimits indicates an expected call of SyncQuotaLimits.
func (mr *MockLifecycleAdminMockRecorder) SyncQuotaLimits(ctx, backends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncQuotaLimits", reflect.TypeOf((*MockLifecycleAdmin)(nil).SyncQuotaLimits), ctx, backends)
}

// VerifySchemaVersion mocks base method.
func (m *MockLifecycleAdmin) VerifySchemaVersion(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySchemaVersion", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifySchemaVersion indicates an expected call of VerifySchemaVersion.
func (mr *MockLifecycleAdminMockRecorder) VerifySchemaVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySchemaVersion", reflect.TypeOf((*MockLifecycleAdmin)(nil).VerifySchemaVersion), ctx)
}
