// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/counter (interfaces: Backend)
//
// Generated by this command:
//
//	mockgen -destination=mock_counter_test.go -package=counter github.com/afreidah/s3-orchestrator/internal/counter Backend
//

// Package counter is a generated GoMock package.
package counter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBackend) Add(backend, field string, delta int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", backend, field, delta)
}

// Add indicates an expected call of Add.
func (mr *MockBackendMockRecorder) Add(backend, field, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBackend)(nil).Add), backend, field, delta)
}

// AddAll mocks base method.
func (m *MockBackend) AddAll(backend string, apiReqs, egress, ingress int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAll", backend, apiReqs, egress, ingress)
}

// AddAll indicates an expected call of AddAll.
func (mr *MockBackendMockRecorder) AddAll(backend, apiReqs, egress, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAll", reflect.TypeOf((*MockBackend)(nil).AddAll), backend, apiReqs, egress, ingress)
}

// Backends mocks base method.
func (m *MockBackend) Backends() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backends")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Backends indicates an expected call of Backends.
func (mr *MockBackendMockRecorder) Backends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backends", reflect.TypeOf((*MockBackend)(nil).Backends))
}

// Load mocks base method.
func (m *MockBackend) Load(backend, field string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", backend, field)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockBackendMockRecorder) Load(backend, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockBackend)(nil).Load), backend, field)
}

// LoadAll mocks base method.
func (m *MockBackend) LoadAll(backend string) LoadAllResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll", backend)
	ret0, _ := ret[0].(LoadAllResult)
	return ret0
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockBackendMockRecorder) LoadAll(backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockBackend)(nil).LoadAll), backend)
}

// Swap mocks base method.
func (m *MockBackend) Swap(backend, field string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Swap", backend, field)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Swap indicates an expected call of Swap.
func (mr *MockBackendMockRecorder) Swap(backend, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Swap", reflect.TypeOf((*MockBackend)(nil).Swap), backend, field)
}
