// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/counter (interfaces: CounterBackend)
//
// Generated by this command:
//
//	mockgen -destination=mock_counter_test.go -package=counter github.com/afreidah/s3-orchestrator/internal/counter CounterBackend
//

// Package counter is a generated GoMock package.
package counter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCounterBackend is a mock of CounterBackend interface.
type MockCounterBackend struct {
	ctrl     *gomock.Controller
	recorder *MockCounterBackendMockRecorder
	isgomock struct{}
}

// MockCounterBackendMockRecorder is the mock recorder for MockCounterBackend.
type MockCounterBackendMockRecorder struct {
	mock *MockCounterBackend
}

// NewMockCounterBackend creates a new mock instance.
func NewMockCounterBackend(ctrl *gomock.Controller) *MockCounterBackend {
	mock := &MockCounterBackend{ctrl: ctrl}
	mock.recorder = &MockCounterBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterBackend) EXPECT() *MockCounterBackendMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCounterBackend) Add(backend, field string, delta int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", backend, field, delta)
}

// Add indicates an expected call of Add.
func (mr *MockCounterBackendMockRecorder) Add(backend, field, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCounterBackend)(nil).Add), backend, field, delta)
}

// AddAll mocks base method.
func (m *MockCounterBackend) AddAll(backend string, apiReqs, egress, ingress int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAll", backend, apiReqs, egress, ingress)
}

// AddAll indicates an expected call of AddAll.
func (mr *MockCounterBackendMockRecorder) AddAll(backend, apiReqs, egress, ingress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAll", reflect.TypeOf((*MockCounterBackend)(nil).AddAll), backend, apiReqs, egress, ingress)
}

// Backends mocks base method.
func (m *MockCounterBackend) Backends() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backends")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Backends indicates an expected call of Backends.
func (mr *MockCounterBackendMockRecorder) Backends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backends", reflect.TypeOf((*MockCounterBackend)(nil).Backends))
}

// Load mocks base method.
func (m *MockCounterBackend) Load(backend, field string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", backend, field)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockCounterBackendMockRecorder) Load(backend, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCounterBackend)(nil).Load), backend, field)
}

// LoadAll mocks base method.
func (m *MockCounterBackend) LoadAll(backend string) LoadAllResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll", backend)
	ret0, _ := ret[0].(LoadAllResult)
	return ret0
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockCounterBackendMockRecorder) LoadAll(backend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockCounterBackend)(nil).LoadAll), backend)
}

// Swap mocks base method.
func (m *MockCounterBackend) Swap(backend, field string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Swap", backend, field)
	ret0, _ := ret[0].(int64)
	return ret0
}

// Swap indicates an expected call of Swap.
func (mr *MockCounterBackendMockRecorder) Swap(backend, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Swap", reflect.TypeOf((*MockCounterBackend)(nil).Swap), backend, field)
}
