// -------------------------------------------------------------------------------
// Admin API - Provisioning DTOs
//
// Author: Alex Freidah
//
// Wire types for bucket, user, credential and grant administration, shared by
// the handler and its clients. Kept in the leaf adminapi package so the server
// and the out-of-process client depend on one definition.
//
// Every listed entry carries the source that declared it, because that is what
// tells a caller whether it can be changed: a config-declared entry is visible
// and read-only. No listing carries a secret; the one place a secret appears is
// the response to the request that minted it.
// -------------------------------------------------------------------------------

package adminapi

// Source values an entry carries, naming which of the two places declared it.
const (
	SourceConfig = "config"
	SourceStore  = "store"
)

// Bucket is one virtual bucket as the API reports it.
type Bucket struct {
	Name                string     `json:"name"`
	MaxMultipartUploads int        `json:"max_multipart_uploads"`
	CORS                []CORSRule `json:"cors,omitempty"`
	Source              string     `json:"source"`
}

// CORSRule mirrors the S3 CORSRule shape a bucket carries.
type CORSRule struct {
	AllowedOrigins []string `json:"allowed_origins"`
	AllowedMethods []string `json:"allowed_methods"`
	AllowedHeaders []string `json:"allowed_headers,omitempty"`
	ExposeHeaders  []string `json:"expose_headers,omitempty"`
	MaxAge         int      `json:"max_age,omitempty"`
}

// User is one identity as the API reports it, with the buckets it reaches.
type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Buckets []string `json:"buckets"`
	Source  string   `json:"source"`
}

// Credential is one keypair as the API reports it. The secret is deliberately
// absent: it is returned once, by the request that minted it, and never read
// back.
type Credential struct {
	AccessKeyID string `json:"access_key_id"`
	UserID      string `json:"user_id"`
	Label       string `json:"label,omitempty"`
	Source      string `json:"source"`
}

// Notice is something the merge of the two sources found that an operator
// should see and that does not stop the instance serving.
type Notice struct {
	Kind   string `json:"kind"`
	Detail string `json:"detail"`
}

// ProvisioningResponse is everything a deployment declares, from both sources.
// One response rather than four endpoints, because the four are only meaningful
// together: a credential names a user, and a user is only useful for the
// buckets it reaches.
type ProvisioningResponse struct {
	Buckets     []Bucket     `json:"buckets"`
	Users       []User       `json:"users"`
	Credentials []Credential `json:"credentials"`
	Notices     []Notice     `json:"notices,omitempty"`
}

// CreateBucketRequest declares a virtual bucket. MaxMultipartUploads of 0 means
// unlimited, matching the config field it mirrors.
type CreateBucketRequest struct {
	Name                string     `json:"name"`
	MaxMultipartUploads int        `json:"max_multipart_uploads,omitempty"`
	CORS                []CORSRule `json:"cors,omitempty"`
}

// CreateUserRequest declares an identity credentials can be issued against. The
// id is generated by the server, so it is unique and survives a rename.
type CreateUserRequest struct {
	Name string `json:"name"`
}

// CreateCredentialRequest mints a keypair for an existing user. The user is
// required: a keypair with no owner is a credential nobody can account for.
// Label is free text an operator uses to say what holds it.
type CreateCredentialRequest struct {
	UserID string `json:"user_id"`
	Label  string `json:"label,omitempty"`
}

// CreateCredentialResponse is the one place a secret crosses the wire. It is
// not stored anywhere it can be read back, so a caller that loses it issues a
// replacement rather than recovering this one.
type CreateCredentialResponse struct {
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
	UserID          string `json:"user_id"`
	Label           string `json:"label,omitempty"`
}

// CreateGrantRequest lets one user reach one bucket.
type CreateGrantRequest struct {
	UserID string `json:"user_id"`
	Bucket string `json:"bucket"`
}

// ProvisioningOperationResponse acknowledges a mutation, naming what it
// changed so a caller replaying a log can tell one call from the next.
type ProvisioningOperationResponse struct {
	Status   string `json:"status"`
	Bucket   string `json:"bucket,omitempty"`
	UserID   string `json:"user_id,omitempty"`
	UserName string `json:"user_name,omitempty"`
}
