// -------------------------------------------------------------------------------
// Admin API - Provisioning DTOs
//
// Author: Alex Freidah
//
// Wire types for bucket, user, credential and grant administration, shared by
// the handler and its clients. Kept in the leaf adminapi package so the server
// and the out-of-process client depend on one definition.
//
// Every listed entry carries the source that declared it, because that is what
// tells a caller whether it can be changed: a config-declared entry is visible
// and read-only. No listing carries a secret; the one place a secret appears is
// the response to the request that minted it.
// -------------------------------------------------------------------------------

package adminapi

// Source values an entry carries, naming which of the two places declared it.
const (
	SourceConfig = "config"
	SourceStore  = "store"
)

// Bucket is one virtual bucket as the API reports it.
type Bucket struct {
	Name                string     `json:"name"`
	MaxMultipartUploads int        `json:"max_multipart_uploads"`
	CORS                []CORSRule `json:"cors,omitempty"`
	Source              string     `json:"source"`
}

// CORSRule mirrors the S3 CORSRule shape a bucket carries.
type CORSRule struct {
	AllowedOrigins []string `json:"allowed_origins"`
	AllowedMethods []string `json:"allowed_methods"`
	AllowedHeaders []string `json:"allowed_headers,omitempty"`
	ExposeHeaders  []string `json:"expose_headers,omitempty"`
	MaxAge         int      `json:"max_age,omitempty"`
}

// User is one identity as the API reports it, with what it reaches. Buckets is
// the plain list of bucket names it reaches. Grants carries the permissions on
// each bucket and control-plane resource; a bucket wildcard is reported as "*",
// followed only by the buckets whose grant differs from it.
type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Buckets []string `json:"buckets"`
	Grants  []Grant  `json:"grants"`
	Source  string   `json:"source"`
}

// Grant is one resource a user reaches and the permissions that reach carries.
// Name is empty on an orchestrator grant, which names no one thing.
type Grant struct {
	Kind        string   `json:"kind"`
	Name        string   `json:"name,omitempty"`
	Permissions []string `json:"permissions"`
}

// Credential is one keypair as the API reports it. The secret is deliberately
// absent: it is returned once, by the request that minted it, and never read
// back.
type Credential struct {
	AccessKeyID string `json:"access_key_id"`
	UserID      string `json:"user_id"`
	Label       string `json:"label,omitempty"`
	Source      string `json:"source"`
}

// Notice is something the merge of the two sources found that an operator
// should see and that does not stop the instance serving.
type Notice struct {
	Kind   string `json:"kind"`
	Detail string `json:"detail"`
}

// ProvisioningResponse is everything a deployment declares, from both sources.
// One response rather than four endpoints, because the four are only meaningful
// together: a credential names a user, and a user is only useful for the
// buckets it reaches.
type ProvisioningResponse struct {
	Buckets     []Bucket     `json:"buckets"`
	Users       []User       `json:"users"`
	Credentials []Credential `json:"credentials"`
	Notices     []Notice     `json:"notices,omitempty"`
}

// CreateBucketRequest declares a virtual bucket. MaxMultipartUploads of 0 means
// unlimited, matching the config field it mirrors.
type CreateBucketRequest struct {
	Name                string     `json:"name"`
	MaxMultipartUploads int        `json:"max_multipart_uploads,omitempty"`
	CORS                []CORSRule `json:"cors,omitempty"`
}

// UpdateBucketRequest declares what a bucket carries; the name is in the path
// and cannot change. The bucket is replaced, not merged: omitting CORS removes
// its rules, and MaxMultipartUploads of 0 means unlimited.
type UpdateBucketRequest struct {
	MaxMultipartUploads int        `json:"max_multipart_uploads,omitempty"`
	CORS                []CORSRule `json:"cors,omitempty"`
}

// CreateUserRequest declares an identity credentials can be issued against. The
// id is generated by the server, so it is unique and survives a rename.
type CreateUserRequest struct {
	Name string `json:"name"`
}

// CreateCredentialRequest registers a keypair against an existing user, which
// is required. Label is free text saying what holds it. AccessKeyID and
// SecretAccessKey register a keypair the caller already holds; they must be
// set together, and omitting both mints one instead.
type CreateCredentialRequest struct {
	UserID          string `json:"user_id"`
	Label           string `json:"label,omitempty"`
	AccessKeyID     string `json:"access_key_id,omitempty"`
	SecretAccessKey string `json:"secret_access_key,omitempty"`
}

// CreateCredentialResponse carries the keypair the request produced. This is
// the only place a minted secret is returned; it cannot be read back later. A
// supplied secret is echoed.
type CreateCredentialResponse struct {
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
	UserID          string `json:"user_id"`
	Label           string `json:"label,omitempty"`
}

// RenameUserRequest changes the name an operator reads an identity by. The ID
// is in the path and does not move: credentials and grants reference it.
type RenameUserRequest struct {
	Name string `json:"name"`
}

// SetGrantRequest declares exactly what a user reaches on one resource. The
// user and resource are in the path; an empty Permissions is refused rather
// than read as every permission, because a declaration saying nothing is more
// likely a mistake than a request for full access.
type SetGrantRequest struct {
	Permissions []string `json:"permissions"`
}

// CreateGrantRequest lets one user reach one resource, with the permissions
// that reach carries. Kind defaults to "bucket". Name may be "*" for every
// resource of the kind, and is omitted on an orchestrator grant. An empty
// Permissions means every permission valid on the kind.
type CreateGrantRequest struct {
	UserID      string   `json:"user_id"`
	Kind        string   `json:"kind,omitempty"`
	Name        string   `json:"name,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

// ProvisioningOperationResponse acknowledges a mutation, naming what it
// changed so a caller replaying a log can tell one call from the next.
type ProvisioningOperationResponse struct {
	Status   string `json:"status"`
	Bucket   string `json:"bucket,omitempty"`
	Resource string `json:"resource,omitempty"`
	UserID   string `json:"user_id,omitempty"`
	UserName string `json:"user_name,omitempty"`
}
