// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drains.sql

package db

import (
	"context"
)

const addDrainedObjects = `-- name: AddDrainedObjects :exec
UPDATE backend_drains
SET objects_moved = objects_moved + $1
WHERE backend_name = $2 AND state = 'draining'
`

type AddDrainedObjectsParams struct {
	Moved       int64
	BackendName string
}

func (q *Queries) AddDrainedObjects(ctx context.Context, arg AddDrainedObjectsParams) error {
	_, err := q.db.Exec(ctx, addDrainedObjects, arg.Moved, arg.BackendName)
	return err
}

const clearDrain = `-- name: ClearDrain :execrows
DELETE FROM backend_drains WHERE backend_name = $1
`

func (q *Queries) ClearDrain(ctx context.Context, backendName string) (int64, error) {
	result, err := q.db.Exec(ctx, clearDrain, backendName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeDrain = `-- name: CompleteDrain :execrows
UPDATE backend_drains
SET state = 'drained', finished_at = NOW()
WHERE backend_drains.backend_name = $1
  AND state = 'draining'
  AND NOT EXISTS (SELECT 1 FROM object_locations ol WHERE ol.backend_name = $1 AND ol.managed)
  AND NOT EXISTS (SELECT 1 FROM pending_objects po WHERE po.backend_name = $1)
  AND NOT EXISTS (SELECT 1 FROM multipart_uploads mu WHERE mu.backend_name = $1)
`

// Marks a drain finished only when nothing it moves is left on the backend: no
// managed object rows, no intents of writes still uploading, and no multipart
// uploads. Unmanaged rows are not counted, because a drain leaves them where
// they are and removing the backend deletes them. One statement reads one
// snapshot, so a write committing meanwhile is seen either as its intent or as
// its row, never as neither. Admission already refuses the backend, so the
// three can only shrink. Zero rows affected means something remains and the
// drain carries on.
func (q *Queries) CompleteDrain(ctx context.Context, backendName string) (int64, error) {
	result, err := q.db.Exec(ctx, completeDrain, backendName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDrains = `-- name: ListDrains :many
SELECT backend_name, state, objects_moved, last_error, started_at, finished_at
FROM backend_drains
ORDER BY backend_name
`

func (q *Queries) ListDrains(ctx context.Context) ([]BackendDrain, error) {
	rows, err := q.db.Query(ctx, listDrains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendDrain{}
	for rows.Next() {
		var i BackendDrain
		if err := rows.Scan(
			&i.BackendName,
			&i.State,
			&i.ObjectsMoved,
			&i.LastError,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDrainFailed = `-- name: MarkDrainFailed :exec
UPDATE backend_drains
SET state = 'failed', last_error = $1::text, finished_at = NOW()
WHERE backend_name = $2 AND state = 'draining'
`

type MarkDrainFailedParams struct {
	Reason      string
	BackendName string
}

func (q *Queries) MarkDrainFailed(ctx context.Context, arg MarkDrainFailedParams) error {
	_, err := q.db.Exec(ctx, markDrainFailed, arg.Reason, arg.BackendName)
	return err
}

const startDrain = `-- name: StartDrain :execrows

INSERT INTO backend_drains (backend_name, state)
VALUES ($1, 'draining')
ON CONFLICT (backend_name) DO UPDATE
SET state = 'draining', objects_moved = 0, last_error = NULL,
    started_at = NOW(), finished_at = NULL
WHERE backend_drains.state = 'failed'
`

// -----------------------------------------------------------------------------
// Backend Drain Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for backend_drains, the durable record of each
// backend's drain. Admission reads the table through backend_capacity; these
// queries are the drain's own lifecycle.
// -----------------------------------------------------------------------------
// Inserts a draining record, or restarts a failed one. Zero rows affected means
// the backend is already draining or drained.
func (q *Queries) StartDrain(ctx context.Context, backendName string) (int64, error) {
	result, err := q.db.Exec(ctx, startDrain, backendName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
