// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: multipart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMultipartUploadsByPrefix = `-- name: CountActiveMultipartUploadsByPrefix :one
SELECT COUNT(*) FROM multipart_uploads
WHERE object_key LIKE $1 || '%' ESCAPE '\'
`

func (q *Queries) CountActiveMultipartUploadsByPrefix(ctx context.Context, prefix *string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMultipartUploadsByPrefix, prefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMultipartUpload = `-- name: CreateMultipartUpload :exec

INSERT INTO multipart_uploads (upload_id, object_key, backend_name, content_type, metadata, encryption_key, key_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type CreateMultipartUploadParams struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
}

// -----------------------------------------------------------------------------
// Multipart Upload Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for multipart_uploads and multipart_parts. Covers
// the upload lifecycle (create, lookup, delete), per-part record/list, the
// prefix-scoped listing the S3 ListMultipartUploads handler needs, the
// stale-upload sweep used by the multipart cleanup background worker, and the
// backfill helpers (ListLegacy*, UpdateUploadEncryption, UpdatePartEncryption)
// the multipart_dek_backfill worker calls when promoting legacy rows to the
// shared-DEK format introduced in migration 00010.
// -----------------------------------------------------------------------------
func (q *Queries) CreateMultipartUpload(ctx context.Context, arg CreateMultipartUploadParams) error {
	_, err := q.db.Exec(ctx, createMultipartUpload,
		arg.UploadID,
		arg.ObjectKey,
		arg.BackendName,
		arg.ContentType,
		arg.Metadata,
		arg.EncryptionKey,
		arg.KeyID,
	)
	return err
}

const deleteMultipartUpload = `-- name: DeleteMultipartUpload :exec
DELETE FROM multipart_uploads
WHERE upload_id = $1
`

func (q *Queries) DeleteMultipartUpload(ctx context.Context, uploadID string) error {
	_, err := q.db.Exec(ctx, deleteMultipartUpload, uploadID)
	return err
}

const deleteMultipartUploadsByBackend = `-- name: DeleteMultipartUploadsByBackend :exec
DELETE FROM multipart_uploads WHERE backend_name = $1
`

func (q *Queries) DeleteMultipartUploadsByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteMultipartUploadsByBackend, backendName)
	return err
}

const getMultipartUpload = `-- name: GetMultipartUpload :one
SELECT upload_id, object_key, backend_name, content_type, metadata, encryption_key, key_id, created_at
FROM multipart_uploads
WHERE upload_id = $1
`

type GetMultipartUploadRow struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetMultipartUpload(ctx context.Context, uploadID string) (GetMultipartUploadRow, error) {
	row := q.db.QueryRow(ctx, getMultipartUpload, uploadID)
	var i GetMultipartUploadRow
	err := row.Scan(
		&i.UploadID,
		&i.ObjectKey,
		&i.BackendName,
		&i.ContentType,
		&i.Metadata,
		&i.EncryptionKey,
		&i.KeyID,
		&i.CreatedAt,
	)
	return i, err
}

const getMultipartUploadsByBackend = `-- name: GetMultipartUploadsByBackend :many
SELECT upload_id, object_key, backend_name, content_type, metadata, encryption_key, key_id, created_at
FROM multipart_uploads
WHERE backend_name = $1
`

type GetMultipartUploadsByBackendRow struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetMultipartUploadsByBackend(ctx context.Context, backendName string) ([]GetMultipartUploadsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getMultipartUploadsByBackend, backendName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMultipartUploadsByBackendRow{}
	for rows.Next() {
		var i GetMultipartUploadsByBackendRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.BackendName,
			&i.ContentType,
			&i.Metadata,
			&i.EncryptionKey,
			&i.KeyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParts = `-- name: GetParts :many
SELECT part_number, etag, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at
FROM multipart_parts
WHERE upload_id = $1
ORDER BY part_number
`

type GetPartsRow struct {
	PartNumber    int32
	Etag          string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetParts(ctx context.Context, uploadID string) ([]GetPartsRow, error) {
	rows, err := q.db.Query(ctx, getParts, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPartsRow{}
	for rows.Next() {
		var i GetPartsRow
		if err := rows.Scan(
			&i.PartNumber,
			&i.Etag,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleMultipartUploads = `-- name: GetStaleMultipartUploads :many
SELECT upload_id, object_key, backend_name, content_type, metadata, encryption_key, key_id, created_at
FROM multipart_uploads
WHERE created_at < $1
`

type GetStaleMultipartUploadsRow struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetStaleMultipartUploads(ctx context.Context, createdAt pgtype.Timestamptz) ([]GetStaleMultipartUploadsRow, error) {
	rows, err := q.db.Query(ctx, getStaleMultipartUploads, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleMultipartUploadsRow{}
	for rows.Next() {
		var i GetStaleMultipartUploadsRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.BackendName,
			&i.ContentType,
			&i.Metadata,
			&i.EncryptionKey,
			&i.KeyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyMultipartUploads = `-- name: ListLegacyMultipartUploads :many
SELECT upload_id, object_key, backend_name, content_type, metadata, encryption_key, key_id, created_at
FROM multipart_uploads
WHERE encryption_key IS NULL
ORDER BY created_at
LIMIT $1
`

type ListLegacyMultipartUploadsRow struct {
	UploadID      string
	ObjectKey     string
	BackendName   string
	ContentType   *string
	Metadata      []byte
	EncryptionKey []byte
	KeyID         *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListLegacyMultipartUploads(ctx context.Context, limit int32) ([]ListLegacyMultipartUploadsRow, error) {
	rows, err := q.db.Query(ctx, listLegacyMultipartUploads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegacyMultipartUploadsRow{}
	for rows.Next() {
		var i ListLegacyMultipartUploadsRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.BackendName,
			&i.ContentType,
			&i.Metadata,
			&i.EncryptionKey,
			&i.KeyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMultipartUploadsByPrefix = `-- name: ListMultipartUploadsByPrefix :many
SELECT upload_id, object_key, content_type, created_at
FROM multipart_uploads
WHERE object_key LIKE $1 || '%' ESCAPE '\'
ORDER BY object_key, created_at
LIMIT $2
`

type ListMultipartUploadsByPrefixParams struct {
	Prefix     *string
	MaxUploads int32
}

type ListMultipartUploadsByPrefixRow struct {
	UploadID    string
	ObjectKey   string
	ContentType *string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListMultipartUploadsByPrefix(ctx context.Context, arg ListMultipartUploadsByPrefixParams) ([]ListMultipartUploadsByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listMultipartUploadsByPrefix, arg.Prefix, arg.MaxUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMultipartUploadsByPrefixRow{}
	for rows.Next() {
		var i ListMultipartUploadsByPrefixRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartEncryption = `-- name: UpdatePartEncryption :exec
UPDATE multipart_parts
SET size_bytes = $3, encrypted = $4, encryption_key = $5, key_id = $6, plaintext_size = $7
WHERE upload_id = $1 AND part_number = $2
`

type UpdatePartEncryptionParams struct {
	UploadID      string
	PartNumber    int32
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

func (q *Queries) UpdatePartEncryption(ctx context.Context, arg UpdatePartEncryptionParams) error {
	_, err := q.db.Exec(ctx, updatePartEncryption,
		arg.UploadID,
		arg.PartNumber,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
	)
	return err
}

const updateUploadEncryption = `-- name: UpdateUploadEncryption :exec
UPDATE multipart_uploads
SET encryption_key = $2, key_id = $3
WHERE upload_id = $1
`

type UpdateUploadEncryptionParams struct {
	UploadID      string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) UpdateUploadEncryption(ctx context.Context, arg UpdateUploadEncryptionParams) error {
	_, err := q.db.Exec(ctx, updateUploadEncryption, arg.UploadID, arg.EncryptionKey, arg.KeyID)
	return err
}

const upsertPart = `-- name: UpsertPart :exec
INSERT INTO multipart_parts (upload_id, part_number, etag, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (upload_id, part_number) DO UPDATE SET
    etag = $3, size_bytes = $4, encrypted = $5, encryption_key = $6, key_id = $7, plaintext_size = $8, created_at = NOW()
`

type UpsertPartParams struct {
	UploadID      string
	PartNumber    int32
	Etag          string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

func (q *Queries) UpsertPart(ctx context.Context, arg UpsertPartParams) error {
	_, err := q.db.Exec(ctx, upsertPart,
		arg.UploadID,
		arg.PartNumber,
		arg.Etag,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
	)
	return err
}
