// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeNotification = `-- name: CompleteNotification :exec
DELETE FROM notification_outbox WHERE id = $1
`

func (q *Queries) CompleteNotification(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeNotification, id)
	return err
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT id, event_type, payload, endpoint_url, attempts
FROM notification_outbox
WHERE next_retry <= NOW() AND attempts < 10
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingNotificationsRow struct {
	ID          int64
	EventType   string
	Payload     []byte
	EndpointUrl string
	Attempts    int32
}

func (q *Queries) GetPendingNotifications(ctx context.Context, limit int32) ([]GetPendingNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingNotificationsRow{}
	for rows.Next() {
		var i GetPendingNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.EndpointUrl,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notification_outbox (event_type, payload, endpoint_url)
VALUES ($1, $2, $3)
`

type InsertNotificationParams struct {
	EventType   string
	Payload     []byte
	EndpointUrl string
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification, arg.EventType, arg.Payload, arg.EndpointUrl)
	return err
}

const retryNotification = `-- name: RetryNotification :exec
UPDATE notification_outbox
SET attempts = attempts + 1,
    next_retry = NOW() + $1::interval,
    last_error = $2
WHERE id = $3
`

type RetryNotificationParams struct {
	Backoff   pgtype.Interval
	LastError *string
	ID        int64
}

func (q *Queries) RetryNotification(ctx context.Context, arg RetryNotificationParams) error {
	_, err := q.db.Exec(ctx, retryNotification, arg.Backoff, arg.LastError, arg.ID)
	return err
}
