// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustBackendBytesUsed = `-- name: AdjustBackendBytesUsed :exec
UPDATE backend_quotas
SET bytes_used = GREATEST(0, bytes_used + $1), updated_at = NOW()
WHERE backend_name = $2
`

type AdjustBackendBytesUsedParams struct {
	Delta       int64
	BackendName string
}

// Applies a signed delta to bytes_used without the bytes_limit guard
// IncrementQuota uses, because the on-disk byte count is reality and
// the counter must follow it whether or not the limit would otherwise
// be exceeded. GREATEST(0, ...) clamps so a delta-arithmetic bug
// cannot drive the counter negative. Used by MarkObjectEncrypted and
// MarkObjectDecrypted to keep bytes_used in step with size_bytes
// after the bulk encrypt-existing / decrypt-existing rewrite path
// changes the on-disk size.
func (q *Queries) AdjustBackendBytesUsed(ctx context.Context, arg AdjustBackendBytesUsedParams) error {
	_, err := q.db.Exec(ctx, adjustBackendBytesUsed, arg.Delta, arg.BackendName)
	return err
}

const decrementOrphanBytes = `-- name: DecrementOrphanBytes :exec
UPDATE backend_quotas
SET orphan_bytes = GREATEST(0, orphan_bytes - $1), updated_at = NOW()
WHERE backend_name = $2
`

type DecrementOrphanBytesParams struct {
	Amount      int64
	BackendName string
}

func (q *Queries) DecrementOrphanBytes(ctx context.Context, arg DecrementOrphanBytesParams) error {
	_, err := q.db.Exec(ctx, decrementOrphanBytes, arg.Amount, arg.BackendName)
	return err
}

const decrementQuota = `-- name: DecrementQuota :exec
UPDATE backend_quotas
SET bytes_used = GREATEST(0, bytes_used - $1), updated_at = NOW()
WHERE backend_name = $2
`

type DecrementQuotaParams struct {
	Amount      int64
	BackendName string
}

func (q *Queries) DecrementQuota(ctx context.Context, arg DecrementQuotaParams) error {
	_, err := q.db.Exec(ctx, decrementQuota, arg.Amount, arg.BackendName)
	return err
}

const deleteQuota = `-- name: DeleteQuota :exec
DELETE FROM backend_quotas WHERE backend_name = $1
`

func (q *Queries) DeleteQuota(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteQuota, backendName)
	return err
}

const getActiveMultipartCountsByBackend = `-- name: GetActiveMultipartCountsByBackend :many
SELECT backend_name, COUNT(*) AS upload_count
FROM multipart_uploads
GROUP BY backend_name
`

type GetActiveMultipartCountsByBackendRow struct {
	BackendName string
	UploadCount int64
}

func (q *Queries) GetActiveMultipartCountsByBackend(ctx context.Context) ([]GetActiveMultipartCountsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getActiveMultipartCountsByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMultipartCountsByBackendRow{}
	for rows.Next() {
		var i GetActiveMultipartCountsByBackendRow
		if err := rows.Scan(&i.BackendName, &i.UploadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllQuotaStats = `-- name: GetAllQuotaStats :many
SELECT backend_name, bytes_used, bytes_limit, orphan_bytes, updated_at
FROM backend_quotas
`

type GetAllQuotaStatsRow struct {
	BackendName string
	BytesUsed   int64
	BytesLimit  int64
	OrphanBytes int64
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetAllQuotaStats(ctx context.Context) ([]GetAllQuotaStatsRow, error) {
	rows, err := q.db.Query(ctx, getAllQuotaStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllQuotaStatsRow{}
	for rows.Next() {
		var i GetAllQuotaStatsRow
		if err := rows.Scan(
			&i.BackendName,
			&i.BytesUsed,
			&i.BytesLimit,
			&i.OrphanBytes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBackendAvailableSpace = `-- name: GetBackendAvailableSpace :one
SELECT CASE
    WHEN q.bytes_limit = 0 THEN 9223372036854775807  -- max int64
    ELSE (q.bytes_limit - q.bytes_used - q.orphan_bytes - COALESCE(m.inflight, 0))
END::bigint AS available
FROM backend_quotas q
LEFT JOIN (
    SELECT mu.backend_name, SUM(mp.size_bytes) AS inflight
    FROM multipart_uploads mu
    JOIN multipart_parts mp ON mp.upload_id = mu.upload_id
    GROUP BY mu.backend_name
) m ON m.backend_name = q.backend_name
WHERE q.backend_name = $1
`

// bytes_limit = 0 means unlimited (no quota enforcement)
func (q *Queries) GetBackendAvailableSpace(ctx context.Context, backendName string) (int64, error) {
	row := q.db.QueryRow(ctx, getBackendAvailableSpace, backendName)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const getLeastUtilizedBackend = `-- name: GetLeastUtilizedBackend :one
SELECT q.backend_name,
       CASE WHEN q.bytes_limit = 0 THEN 9223372036854775807
            ELSE (q.bytes_limit - q.bytes_used - q.orphan_bytes - COALESCE(m.inflight, 0))
       END::bigint AS available
FROM backend_quotas q
LEFT JOIN (
    SELECT mu.backend_name, SUM(mp.size_bytes) AS inflight
    FROM multipart_uploads mu
    JOIN multipart_parts mp ON mp.upload_id = mu.upload_id
    GROUP BY mu.backend_name
) m ON m.backend_name = q.backend_name
WHERE q.backend_name = ANY($1::text[])
  AND CASE WHEN q.bytes_limit = 0 THEN 9223372036854775807
           ELSE (q.bytes_limit - q.bytes_used - q.orphan_bytes - COALESCE(m.inflight, 0))
      END >= $2::bigint
ORDER BY CASE WHEN q.bytes_limit = 0 THEN 0
              ELSE (q.bytes_used + q.orphan_bytes)::float8 / q.bytes_limit::float8
         END ASC
LIMIT 1
`

type GetLeastUtilizedBackendParams struct {
	BackendNames []string
	MinSize      int64
}

type GetLeastUtilizedBackendRow struct {
	BackendName string
	Available   int64
}

// Finds the backend with the lowest utilization ratio that has enough space.
func (q *Queries) GetLeastUtilizedBackend(ctx context.Context, arg GetLeastUtilizedBackendParams) (GetLeastUtilizedBackendRow, error) {
	row := q.db.QueryRow(ctx, getLeastUtilizedBackend, arg.BackendNames, arg.MinSize)
	var i GetLeastUtilizedBackendRow
	err := row.Scan(&i.BackendName, &i.Available)
	return i, err
}

const getObjectCountsByBackend = `-- name: GetObjectCountsByBackend :many
SELECT backend_name, COUNT(*) AS object_count
FROM object_locations
GROUP BY backend_name
`

type GetObjectCountsByBackendRow struct {
	BackendName string
	ObjectCount int64
}

func (q *Queries) GetObjectCountsByBackend(ctx context.Context) ([]GetObjectCountsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getObjectCountsByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectCountsByBackendRow{}
	for rows.Next() {
		var i GetObjectCountsByBackendRow
		if err := rows.Scan(&i.BackendName, &i.ObjectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObjectSizeBytes = `-- name: GetObjectSizeBytes :one
SELECT size_bytes FROM object_locations
WHERE object_key = $1 AND backend_name = $2
`

type GetObjectSizeBytesParams struct {
	ObjectKey   string
	BackendName string
}

// Returns the current size_bytes of an object_locations row. Used
// inside MarkObjectDecrypted so the caller can compute the size
// delta against the row that is about to be overwritten without
// needing the old ciphertext size to flow through the API.
func (q *Queries) GetObjectSizeBytes(ctx context.Context, arg GetObjectSizeBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getObjectSizeBytes, arg.ObjectKey, arg.BackendName)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}

const getUnverifiedObjectCountsByBackend = `-- name: GetUnverifiedObjectCountsByBackend :many
SELECT backend_name, COUNT(*) AS object_count
FROM object_locations
WHERE content_hash IS NULL
GROUP BY backend_name
`

type GetUnverifiedObjectCountsByBackendRow struct {
	BackendName string
	ObjectCount int64
}

func (q *Queries) GetUnverifiedObjectCountsByBackend(ctx context.Context) ([]GetUnverifiedObjectCountsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getUnverifiedObjectCountsByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnverifiedObjectCountsByBackendRow{}
	for rows.Next() {
		var i GetUnverifiedObjectCountsByBackendRow
		if err := rows.Scan(&i.BackendName, &i.ObjectCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOrphanBytes = `-- name: IncrementOrphanBytes :exec
UPDATE backend_quotas
SET orphan_bytes = orphan_bytes + $1, updated_at = NOW()
WHERE backend_name = $2
`

type IncrementOrphanBytesParams struct {
	Amount      int64
	BackendName string
}

func (q *Queries) IncrementOrphanBytes(ctx context.Context, arg IncrementOrphanBytesParams) error {
	_, err := q.db.Exec(ctx, incrementOrphanBytes, arg.Amount, arg.BackendName)
	return err
}

const incrementQuota = `-- name: IncrementQuota :execrows
UPDATE backend_quotas
SET bytes_used = bytes_used + $1, updated_at = NOW()
WHERE backend_name = $2
  AND (bytes_limit = 0 OR bytes_used + orphan_bytes + $1 <= bytes_limit)
`

type IncrementQuotaParams struct {
	Amount      int64
	BackendName string
}

func (q *Queries) IncrementQuota(ctx context.Context, arg IncrementQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementQuota, arg.Amount, arg.BackendName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBackendQuotaUsage = `-- name: ListBackendQuotaUsage :many
SELECT q.backend_name,
       q.bytes_limit,
       q.bytes_used,
       q.orphan_bytes,
       COALESCE(m.inflight, 0)::bigint AS inflight_bytes
FROM backend_quotas q
LEFT JOIN (
    SELECT mu.backend_name, SUM(mp.size_bytes) AS inflight
    FROM multipart_uploads mu
    JOIN multipart_parts mp ON mp.upload_id = mu.upload_id
    GROUP BY mu.backend_name
) m ON m.backend_name = q.backend_name
`

type ListBackendQuotaUsageRow struct {
	BackendName   string
	BytesLimit    int64
	BytesUsed     int64
	OrphanBytes   int64
	InflightBytes int64
}

// Every backend's ceiling and what occupies it: the counter, orphans awaiting
// cleanup, and the parts of uploads that have not completed. The same three
// terms GetBackendWithSpace subtracts, read for the whole fleet in one pass
// rather than per candidate, because the quota tracker refreshes its baseline
// once per flush instead of asking on every write.
func (q *Queries) ListBackendQuotaUsage(ctx context.Context) ([]ListBackendQuotaUsageRow, error) {
	rows, err := q.db.Query(ctx, listBackendQuotaUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackendQuotaUsageRow{}
	for rows.Next() {
		var i ListBackendQuotaUsageRow
		if err := rows.Scan(
			&i.BackendName,
			&i.BytesLimit,
			&i.BytesUsed,
			&i.OrphanBytes,
			&i.InflightBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackendBytesUsed = `-- name: SetBackendBytesUsed :exec
UPDATE backend_quotas
SET bytes_used = $1, updated_at = NOW()
WHERE backend_name = $2
`

type SetBackendBytesUsedParams struct {
	BytesUsed   int64
	BackendName string
}

// Overwrites bytes_used with an authoritative value (no bytes_limit guard,
// because the recomputed total is reality and the counter must follow it).
func (q *Queries) SetBackendBytesUsed(ctx context.Context, arg SetBackendBytesUsedParams) error {
	_, err := q.db.Exec(ctx, setBackendBytesUsed, arg.BytesUsed, arg.BackendName)
	return err
}

const sumObjectSizesByBackend = `-- name: SumObjectSizesByBackend :many
SELECT backend_name, COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes
FROM object_locations
GROUP BY backend_name
`

type SumObjectSizesByBackendRow struct {
	BackendName string
	TotalBytes  int64
}

// Authoritative per-backend byte total from the object ledger. Used by usage
// reconciliation to recompute bytes_used, which is otherwise an incrementally
// maintained counter that drifts if any mutation path misses an adjustment.
func (q *Queries) SumObjectSizesByBackend(ctx context.Context) ([]SumObjectSizesByBackendRow, error) {
	rows, err := q.db.Query(ctx, sumObjectSizesByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumObjectSizesByBackendRow{}
	for rows.Next() {
		var i SumObjectSizesByBackendRow
		if err := rows.Scan(&i.BackendName, &i.TotalBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuotaLimit = `-- name: UpsertQuotaLimit :exec

INSERT INTO backend_quotas (backend_name, bytes_limit, bytes_used, updated_at)
VALUES ($1, $2, 0, NOW())
ON CONFLICT (backend_name) DO UPDATE SET
    bytes_limit = $2,
    updated_at = NOW()
`

type UpsertQuotaLimitParams struct {
	BackendName string
	BytesLimit  int64
}

// -----------------------------------------------------------------------------
// Quota Queries
//
// Author: Alex Freidah
//
// sqlc-input definitions for backend_quotas - the per-backend bytes_used,
// bytes_limit, and orphan_bytes counters. The increment query is guarded
// (WHERE bytes_used + delta <= bytes_limit) so an INSERT exceeding the
// limit touches zero rows and the engine returns ErrNoSpaceAvailable. Lock
// acquisition order across multi-row updates is enforced at the call site
// (sorted backend_name) to avoid deadlock.
// -----------------------------------------------------------------------------
func (q *Queries) UpsertQuotaLimit(ctx context.Context, arg UpsertQuotaLimitParams) error {
	_, err := q.db.Exec(ctx, upsertQuotaLimit, arg.BackendName, arg.BytesLimit)
	return err
}
