// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/proxy/metrics (interfaces: Deps)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=metrics github.com/afreidah/s3-orchestrator/internal/proxy/metrics Deps
//

// Package metrics is a generated GoMock package.
package metrics

import (
	context "context"
	reflect "reflect"

	core "github.com/afreidah/s3-orchestrator/internal/store/core"
	gomock "go.uber.org/mock/gomock"
)

// MockDeps is a mock of Deps interface.
type MockDeps struct {
	ctrl     *gomock.Controller
	recorder *MockDepsMockRecorder
	isgomock struct{}
}

// MockDepsMockRecorder is the mock recorder for MockDeps.
type MockDepsMockRecorder struct {
	mock *MockDeps
}

// NewMockDeps creates a new mock instance.
func NewMockDeps(ctrl *gomock.Controller) *MockDeps {
	mock := &MockDeps{ctrl: ctrl}
	mock.recorder = &MockDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeps) EXPECT() *MockDepsMockRecorder {
	return m.recorder
}

// CountReplicationBacklog mocks base method.
func (m *MockDeps) CountReplicationBacklog(ctx context.Context, factor int) (core.ReplicationBacklog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReplicationBacklog", ctx, factor)
	ret0, _ := ret[0].(core.ReplicationBacklog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReplicationBacklog indicates an expected call of CountReplicationBacklog.
func (mr *MockDepsMockRecorder) CountReplicationBacklog(ctx, factor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReplicationBacklog", reflect.TypeOf((*MockDeps)(nil).CountReplicationBacklog), ctx, factor)
}

// GetActiveMultipartCounts mocks base method.
func (m *MockDeps) GetActiveMultipartCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMultipartCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMultipartCounts indicates an expected call of GetActiveMultipartCounts.
func (mr *MockDepsMockRecorder) GetActiveMultipartCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMultipartCounts", reflect.TypeOf((*MockDeps)(nil).GetActiveMultipartCounts), ctx)
}

// GetPoolUsageForPeriod mocks base method.
func (m *MockDeps) GetPoolUsageForPeriod(ctx context.Context, period string) (map[string]core.PoolUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolUsageForPeriod", ctx, period)
	ret0, _ := ret[0].(map[string]core.PoolUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoolUsageForPeriod indicates an expected call of GetPoolUsageForPeriod.
func (mr *MockDepsMockRecorder) GetPoolUsageForPeriod(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolUsageForPeriod", reflect.TypeOf((*MockDeps)(nil).GetPoolUsageForPeriod), ctx, period)
}

// GetQuotaStats mocks base method.
func (m *MockDeps) GetQuotaStats(ctx context.Context) (map[string]core.QuotaStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaStats", ctx)
	ret0, _ := ret[0].(map[string]core.QuotaStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaStats indicates an expected call of GetQuotaStats.
func (mr *MockDepsMockRecorder) GetQuotaStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaStats", reflect.TypeOf((*MockDeps)(nil).GetQuotaStats), ctx)
}

// GetUsageForPeriod mocks base method.
func (m *MockDeps) GetUsageForPeriod(ctx context.Context, period string) (map[string]core.UsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsageForPeriod", ctx, period)
	ret0, _ := ret[0].(map[string]core.UsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsageForPeriod indicates an expected call of GetUsageForPeriod.
func (mr *MockDepsMockRecorder) GetUsageForPeriod(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsageForPeriod", reflect.TypeOf((*MockDeps)(nil).GetUsageForPeriod), ctx, period)
}

// LedgerStats mocks base method.
func (m *MockDeps) LedgerStats(ctx context.Context) (core.LedgerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LedgerStats", ctx)
	ret0, _ := ret[0].(core.LedgerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LedgerStats indicates an expected call of LedgerStats.
func (mr *MockDepsMockRecorder) LedgerStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LedgerStats", reflect.TypeOf((*MockDeps)(nil).LedgerStats), ctx)
}
