// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingCleanups = `-- name: CountPendingCleanups :one
SELECT COUNT(*) FROM cleanup_queue WHERE attempts < 10
`

func (q *Queries) CountPendingCleanups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCleanups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCleanupItem = `-- name: DeleteCleanupItem :exec
DELETE FROM cleanup_queue WHERE id = $1
`

func (q *Queries) DeleteCleanupItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCleanupItem, id)
	return err
}

const enqueueCleanup = `-- name: EnqueueCleanup :exec
INSERT INTO cleanup_queue (backend_name, object_key, reason)
VALUES ($1, $2, $3)
`

type EnqueueCleanupParams struct {
	BackendName string
	ObjectKey   string
	Reason      string
}

func (q *Queries) EnqueueCleanup(ctx context.Context, arg EnqueueCleanupParams) error {
	_, err := q.db.Exec(ctx, enqueueCleanup, arg.BackendName, arg.ObjectKey, arg.Reason)
	return err
}

const getPendingCleanups = `-- name: GetPendingCleanups :many
SELECT id, backend_name, object_key, reason, attempts
FROM cleanup_queue
WHERE next_retry <= NOW() AND attempts < 10
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingCleanupsRow struct {
	ID          int64
	BackendName string
	ObjectKey   string
	Reason      string
	Attempts    int32
}

func (q *Queries) GetPendingCleanups(ctx context.Context, limit int32) ([]GetPendingCleanupsRow, error) {
	rows, err := q.db.Query(ctx, getPendingCleanups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingCleanupsRow{}
	for rows.Next() {
		var i GetPendingCleanupsRow
		if err := rows.Scan(
			&i.ID,
			&i.BackendName,
			&i.ObjectKey,
			&i.Reason,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCleanupRetry = `-- name: UpdateCleanupRetry :exec
UPDATE cleanup_queue
SET attempts = attempts + 1,
    next_retry = NOW() + $1::interval,
    last_error = $2
WHERE id = $3
`

type UpdateCleanupRetryParams struct {
	Backoff   pgtype.Interval
	LastError *string
	ID        int64
}

func (q *Queries) UpdateCleanupRetry(ctx context.Context, arg UpdateCleanupRetryParams) error {
	_, err := q.db.Exec(ctx, updateCleanupRetry, arg.Backoff, arg.LastError, arg.ID)
	return err
}
