// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backendObjectStats = `-- name: BackendObjectStats :one
SELECT COUNT(*) AS object_count, COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes
FROM object_locations
WHERE backend_name = $1
`

type BackendObjectStatsRow struct {
	ObjectCount int64
	TotalBytes  int64
}

func (q *Queries) BackendObjectStats(ctx context.Context, backendName string) (BackendObjectStatsRow, error) {
	row := q.db.QueryRow(ctx, backendObjectStats, backendName)
	var i BackendObjectStatsRow
	err := row.Scan(&i.ObjectCount, &i.TotalBytes)
	return i, err
}

const checkObjectExistsOnBackend = `-- name: CheckObjectExistsOnBackend :one
SELECT EXISTS(
    SELECT 1 FROM object_locations
    WHERE object_key = $1 AND backend_name = $2
) AS exists
`

type CheckObjectExistsOnBackendParams struct {
	ObjectKey   string
	BackendName string
}

func (q *Queries) CheckObjectExistsOnBackend(ctx context.Context, arg CheckObjectExistsOnBackendParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkObjectExistsOnBackend, arg.ObjectKey, arg.BackendName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteObjectCopies = `-- name: DeleteObjectCopies :exec
DELETE FROM object_locations
WHERE object_key = $1
`

func (q *Queries) DeleteObjectCopies(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deleteObjectCopies, objectKey)
	return err
}

const deleteObjectFromBackend = `-- name: DeleteObjectFromBackend :exec
DELETE FROM object_locations
WHERE object_key = $1 AND backend_name = $2
`

type DeleteObjectFromBackendParams struct {
	ObjectKey   string
	BackendName string
}

func (q *Queries) DeleteObjectFromBackend(ctx context.Context, arg DeleteObjectFromBackendParams) error {
	_, err := q.db.Exec(ctx, deleteObjectFromBackend, arg.ObjectKey, arg.BackendName)
	return err
}

const deleteObjectLocationsByBackend = `-- name: DeleteObjectLocationsByBackend :exec
DELETE FROM object_locations WHERE backend_name = $1
`

func (q *Queries) DeleteObjectLocationsByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteObjectLocationsByBackend, backendName)
	return err
}

const getAllObjectLocations = `-- name: GetAllObjectLocations :many
SELECT object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at
FROM object_locations
WHERE object_key = $1
ORDER BY created_at ASC
`

type GetAllObjectLocationsRow struct {
	ObjectKey     string
	BackendName   string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetAllObjectLocations(ctx context.Context, objectKey string) ([]GetAllObjectLocationsRow, error) {
	rows, err := q.db.Query(ctx, getAllObjectLocations, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllObjectLocationsRow{}
	for rows.Next() {
		var i GetAllObjectLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectoryStats = `-- name: GetDirectoryStats :many
SELECT
    (CASE WHEN position('/' IN substring(object_key FROM length($1::text) + 1)) > 0
         THEN substring(object_key FROM length($1::text) + 1
              FOR position('/' IN substring(object_key FROM length($1::text) + 1)))
         ELSE substring(object_key FROM length($1::text) + 1)
    END)::text AS name,
    (CASE WHEN position('/' IN substring(object_key FROM length($1::text) + 1)) > 0
         THEN true ELSE false
    END)::boolean AS is_dir,
    COUNT(*)  AS file_count,
    COALESCE(SUM(size_bytes), 0)::bigint AS total_size
FROM (
    SELECT DISTINCT ON (object_key) object_key, size_bytes
    FROM object_locations
    WHERE object_key LIKE $1::text || '%' ESCAPE '\'
      AND length(object_key) > length($1::text)
    ORDER BY object_key, created_at ASC
) deduped
GROUP BY name, is_dir
ORDER BY is_dir DESC, name ASC
`

type GetDirectoryStatsRow struct {
	Name      string
	IsDir     bool
	FileCount int64
	TotalSize int64
}

// Aggregate count and size for immediate children of a directory prefix.
// Directories (containing a '/') and files are distinguished by is_dir.
// Uses a subquery to deduplicate replicated objects before summing sizes.
func (q *Queries) GetDirectoryStats(ctx context.Context, prefix string) ([]GetDirectoryStatsRow, error) {
	rows, err := q.db.Query(ctx, getDirectoryStats, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDirectoryStatsRow{}
	for rows.Next() {
		var i GetDirectoryStatsRow
		if err := rows.Scan(
			&i.Name,
			&i.IsDir,
			&i.FileCount,
			&i.TotalSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingCopiesForUpdate = `-- name: GetExistingCopiesForUpdate :many
SELECT backend_name, size_bytes
FROM object_locations
WHERE object_key = $1
FOR UPDATE
`

type GetExistingCopiesForUpdateRow struct {
	BackendName string
	SizeBytes   int64
}

func (q *Queries) GetExistingCopiesForUpdate(ctx context.Context, objectKey string) ([]GetExistingCopiesForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getExistingCopiesForUpdate, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExistingCopiesForUpdateRow{}
	for rows.Next() {
		var i GetExistingCopiesForUpdateRow
		if err := rows.Scan(&i.BackendName, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertObjectLocation = `-- name: InsertObjectLocation :exec
INSERT INTO object_locations (object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type InsertObjectLocationParams struct {
	ObjectKey     string
	BackendName   string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

func (q *Queries) InsertObjectLocation(ctx context.Context, arg InsertObjectLocationParams) error {
	_, err := q.db.Exec(ctx, insertObjectLocation,
		arg.ObjectKey,
		arg.BackendName,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
	)
	return err
}

const insertObjectLocationIfNotExists = `-- name: InsertObjectLocationIfNotExists :one
INSERT INTO object_locations (object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (object_key, backend_name) DO NOTHING
RETURNING true AS inserted
`

type InsertObjectLocationIfNotExistsParams struct {
	ObjectKey     string
	BackendName   string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

func (q *Queries) InsertObjectLocationIfNotExists(ctx context.Context, arg InsertObjectLocationIfNotExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertObjectLocationIfNotExists,
		arg.ObjectKey,
		arg.BackendName,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const listDirectChildren = `-- name: ListDirectChildren :many
SELECT DISTINCT ON (object_key) object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND position('/' IN substring(object_key FROM length($1::text) + 1)) = 0
  AND length(object_key) > length($1::text)
  AND object_key > $2
ORDER BY object_key, created_at ASC
LIMIT $3
`

type ListDirectChildrenParams struct {
	Prefix     string
	StartAfter string
	MaxKeys    int32
}

type ListDirectChildrenRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

// Return per-file detail for non-directory children under a prefix, with pagination.
func (q *Queries) ListDirectChildren(ctx context.Context, arg ListDirectChildrenParams) ([]ListDirectChildrenRow, error) {
	rows, err := q.db.Query(ctx, listDirectChildren, arg.Prefix, arg.StartAfter, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectChildrenRow{}
	for rows.Next() {
		var i ListDirectChildrenRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedLocations = `-- name: ListEncryptedLocations :many
SELECT object_key, backend_name, encryption_key, key_id
FROM object_locations
WHERE encrypted = TRUE AND key_id = $1
ORDER BY object_key, backend_name
LIMIT $2 OFFSET $3
`

type ListEncryptedLocationsParams struct {
	KeyID  *string
	Limit  int32
	Offset int32
}

type ListEncryptedLocationsRow struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) ListEncryptedLocations(ctx context.Context, arg ListEncryptedLocationsParams) ([]ListEncryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listEncryptedLocations, arg.KeyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEncryptedLocationsRow{}
	for rows.Next() {
		var i ListEncryptedLocationsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.EncryptionKey,
			&i.KeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredObjects = `-- name: ListExpiredObjects :many
SELECT DISTINCT ON (object_key) object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND created_at < $2
ORDER BY object_key, created_at ASC
LIMIT $3
`

type ListExpiredObjectsParams struct {
	Prefix  string
	Cutoff  pgtype.Timestamptz
	MaxKeys int32
}

type ListExpiredObjectsRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListExpiredObjects(ctx context.Context, arg ListExpiredObjectsParams) ([]ListExpiredObjectsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredObjects, arg.Prefix, arg.Cutoff, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredObjectsRow{}
	for rows.Next() {
		var i ListExpiredObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByBackend = `-- name: ListObjectsByBackend :many
SELECT object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE backend_name = $1
ORDER BY size_bytes ASC
LIMIT $2
`

type ListObjectsByBackendParams struct {
	BackendName string
	Limit       int32
}

type ListObjectsByBackendRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListObjectsByBackend(ctx context.Context, arg ListObjectsByBackendParams) ([]ListObjectsByBackendRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByBackend, arg.BackendName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByBackendRow{}
	for rows.Next() {
		var i ListObjectsByBackendRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectsByPrefix = `-- name: ListObjectsByPrefix :many
SELECT DISTINCT ON (object_key) object_key, backend_name, size_bytes, created_at
FROM object_locations
WHERE object_key LIKE $1::text || '%' ESCAPE '\'
  AND object_key > $2
ORDER BY object_key, created_at ASC
LIMIT $3
`

type ListObjectsByPrefixParams struct {
	Prefix     string
	StartAfter string
	MaxKeys    int32
}

type ListObjectsByPrefixRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListObjectsByPrefix(ctx context.Context, arg ListObjectsByPrefixParams) ([]ListObjectsByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listObjectsByPrefix, arg.Prefix, arg.StartAfter, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsByPrefixRow{}
	for rows.Next() {
		var i ListObjectsByPrefixRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnencryptedLocations = `-- name: ListUnencryptedLocations :many
SELECT object_key, backend_name, size_bytes
FROM object_locations
WHERE encrypted = FALSE
ORDER BY object_key, backend_name
LIMIT $1 OFFSET $2
`

type ListUnencryptedLocationsParams struct {
	Limit  int32
	Offset int32
}

type ListUnencryptedLocationsRow struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
}

func (q *Queries) ListUnencryptedLocations(ctx context.Context, arg ListUnencryptedLocationsParams) ([]ListUnencryptedLocationsRow, error) {
	rows, err := q.db.Query(ctx, listUnencryptedLocations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnencryptedLocationsRow{}
	for rows.Next() {
		var i ListUnencryptedLocationsRow
		if err := rows.Scan(&i.ObjectKey, &i.BackendName, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockObjectOnBackend = `-- name: LockObjectOnBackend :one
SELECT size_bytes, encrypted, encryption_key, key_id, plaintext_size
FROM object_locations
WHERE object_key = $1 AND backend_name = $2
FOR UPDATE
`

type LockObjectOnBackendParams struct {
	ObjectKey   string
	BackendName string
}

type LockObjectOnBackendRow struct {
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

func (q *Queries) LockObjectOnBackend(ctx context.Context, arg LockObjectOnBackendParams) (LockObjectOnBackendRow, error) {
	row := q.db.QueryRow(ctx, lockObjectOnBackend, arg.ObjectKey, arg.BackendName)
	var i LockObjectOnBackendRow
	err := row.Scan(
		&i.SizeBytes,
		&i.Encrypted,
		&i.EncryptionKey,
		&i.KeyID,
		&i.PlaintextSize,
	)
	return i, err
}

const markObjectEncrypted = `-- name: MarkObjectEncrypted :exec
UPDATE object_locations
SET encrypted = TRUE,
    encryption_key = $3,
    key_id = $4,
    plaintext_size = $5,
    size_bytes = $6
WHERE object_key = $1 AND backend_name = $2
`

type MarkObjectEncryptedParams struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	SizeBytes     int64
}

func (q *Queries) MarkObjectEncrypted(ctx context.Context, arg MarkObjectEncryptedParams) error {
	_, err := q.db.Exec(ctx, markObjectEncrypted,
		arg.ObjectKey,
		arg.BackendName,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
		arg.SizeBytes,
	)
	return err
}

const updateEncryptionKey = `-- name: UpdateEncryptionKey :exec
UPDATE object_locations
SET encryption_key = $3, key_id = $4
WHERE object_key = $1 AND backend_name = $2
`

type UpdateEncryptionKeyParams struct {
	ObjectKey     string
	BackendName   string
	EncryptionKey []byte
	KeyID         *string
}

func (q *Queries) UpdateEncryptionKey(ctx context.Context, arg UpdateEncryptionKeyParams) error {
	_, err := q.db.Exec(ctx, updateEncryptionKey,
		arg.ObjectKey,
		arg.BackendName,
		arg.EncryptionKey,
		arg.KeyID,
	)
	return err
}
