// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replication.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnderReplicatedObjects = `-- name: GetUnderReplicatedObjects :many
WITH under_replicated AS (
    SELECT object_key
    FROM object_locations
    GROUP BY object_key
    HAVING COUNT(*) < $1::bigint
    LIMIT $2
)
SELECT ol.object_key, ol.backend_name, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, ol.created_at
FROM object_locations ol
JOIN under_replicated ur ON ol.object_key = ur.object_key
ORDER BY ol.object_key, ol.created_at ASC
`

type GetUnderReplicatedObjectsParams struct {
	Factor  int64
	MaxKeys int32
}

type GetUnderReplicatedObjectsRow struct {
	ObjectKey     string
	BackendName   string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUnderReplicatedObjects(ctx context.Context, arg GetUnderReplicatedObjectsParams) ([]GetUnderReplicatedObjectsRow, error) {
	rows, err := q.db.Query(ctx, getUnderReplicatedObjects, arg.Factor, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnderReplicatedObjectsRow{}
	for rows.Next() {
		var i GetUnderReplicatedObjectsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnderReplicatedObjectsExcluding = `-- name: GetUnderReplicatedObjectsExcluding :many
WITH under_replicated AS (
    SELECT object_key
    FROM object_locations
    WHERE backend_name != ALL($1::text[])
    GROUP BY object_key
    HAVING COUNT(*) < $2::bigint
    LIMIT $3
)
SELECT ol.object_key, ol.backend_name, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, ol.created_at
FROM object_locations ol
JOIN under_replicated ur ON ol.object_key = ur.object_key
ORDER BY ol.object_key, ol.created_at ASC
`

type GetUnderReplicatedObjectsExcludingParams struct {
	Excluded []string
	Factor   int64
	MaxKeys  int32
}

type GetUnderReplicatedObjectsExcludingRow struct {
	ObjectKey     string
	BackendName   string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUnderReplicatedObjectsExcluding(ctx context.Context, arg GetUnderReplicatedObjectsExcludingParams) ([]GetUnderReplicatedObjectsExcludingRow, error) {
	rows, err := q.db.Query(ctx, getUnderReplicatedObjectsExcluding, arg.Excluded, arg.Factor, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnderReplicatedObjectsExcludingRow{}
	for rows.Next() {
		var i GetUnderReplicatedObjectsExcludingRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReplicaConditional = `-- name: InsertReplicaConditional :one
INSERT INTO object_locations (object_key, backend_name, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at)
SELECT $1, $2, ol.size_bytes, ol.encrypted, ol.encryption_key, ol.key_id, ol.plaintext_size, NOW()
FROM object_locations ol
WHERE ol.object_key = $1 AND ol.backend_name = $3
ON CONFLICT (object_key, backend_name) DO NOTHING
RETURNING true AS inserted
`

type InsertReplicaConditionalParams struct {
	ObjectKey     string
	BackendName   string
	BackendName_2 string
}

func (q *Queries) InsertReplicaConditional(ctx context.Context, arg InsertReplicaConditionalParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertReplicaConditional, arg.ObjectKey, arg.BackendName, arg.BackendName_2)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
