// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/worker (interfaces: Ops,CleanupDeps,ScrubberDeps,BackendSyncer)
//
// Generated by this command:
//
//	mockgen -destination=mock_ops_test.go -package=worker github.com/afreidah/s3-orchestrator/internal/worker Ops,CleanupDeps,ScrubberDeps,BackendSyncer
//

// Package worker is a generated GoMock package.
package worker

import (
	context "context"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	counter "github.com/afreidah/s3-orchestrator/internal/counter"
	store "github.com/afreidah/s3-orchestrator/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockOps is a mock of Ops interface.
type MockOps struct {
	ctrl     *gomock.Controller
	recorder *MockOpsMockRecorder
	isgomock struct{}
}

// MockOpsMockRecorder is the mock recorder for MockOps.
type MockOpsMockRecorder struct {
	mock *MockOps
}

// NewMockOps creates a new mock instance.
func NewMockOps(ctrl *gomock.Controller) *MockOps {
	mock := &MockOps{ctrl: ctrl}
	mock.recorder = &MockOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOps) EXPECT() *MockOpsMockRecorder {
	return m.recorder
}

// AcquireAdmission mocks base method.
func (m *MockOps) AcquireAdmission(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAdmission", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcquireAdmission indicates an expected call of AcquireAdmission.
func (mr *MockOpsMockRecorder) AcquireAdmission(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAdmission", reflect.TypeOf((*MockOps)(nil).AcquireAdmission), ctx)
}

// BackendOrder mocks base method.
func (m *MockOps) BackendOrder() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendOrder")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BackendOrder indicates an expected call of BackendOrder.
func (mr *MockOpsMockRecorder) BackendOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendOrder", reflect.TypeOf((*MockOps)(nil).BackendOrder))
}

// Backends mocks base method.
func (m *MockOps) Backends() map[string]backend.ObjectBackend {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backends")
	ret0, _ := ret[0].(map[string]backend.ObjectBackend)
	return ret0
}

// Backends indicates an expected call of Backends.
func (mr *MockOpsMockRecorder) Backends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backends", reflect.TypeOf((*MockOps)(nil).Backends))
}

// DeleteOrEnqueue mocks base method.
func (m *MockOps) DeleteOrEnqueue(ctx context.Context, be backend.ObjectBackend, backendName, key, reason string, sizeBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrEnqueue", ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteOrEnqueue indicates an expected call of DeleteOrEnqueue.
func (mr *MockOpsMockRecorder) DeleteOrEnqueue(ctx, be, backendName, key, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrEnqueue", reflect.TypeOf((*MockOps)(nil).DeleteOrEnqueue), ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteWithTimeout mocks base method.
func (m *MockOps) DeleteWithTimeout(ctx context.Context, be backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeout", ctx, be, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTimeout indicates an expected call of DeleteWithTimeout.
func (mr *MockOpsMockRecorder) DeleteWithTimeout(ctx, be, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeout", reflect.TypeOf((*MockOps)(nil).DeleteWithTimeout), ctx, be, key)
}

// ExcludeDraining mocks base method.
func (m *MockOps) ExcludeDraining(eligible []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExcludeDraining", eligible)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ExcludeDraining indicates an expected call of ExcludeDraining.
func (mr *MockOpsMockRecorder) ExcludeDraining(eligible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExcludeDraining", reflect.TypeOf((*MockOps)(nil).ExcludeDraining), eligible)
}

// GetBackend mocks base method.
func (m *MockOps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockOpsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockOps)(nil).GetBackend), name)
}

// IsDraining mocks base method.
func (m *MockOps) IsDraining(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDraining", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDraining indicates an expected call of IsDraining.
func (mr *MockOpsMockRecorder) IsDraining(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDraining", reflect.TypeOf((*MockOps)(nil).IsDraining), name)
}

// ReleaseAdmission mocks base method.
func (m *MockOps) ReleaseAdmission() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseAdmission")
}

// ReleaseAdmission indicates an expected call of ReleaseAdmission.
func (mr *MockOpsMockRecorder) ReleaseAdmission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAdmission", reflect.TypeOf((*MockOps)(nil).ReleaseAdmission))
}

// Store mocks base method.
func (m *MockOps) Store() store.MetadataStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(store.MetadataStore)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockOpsMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockOps)(nil).Store))
}

// StreamCopy mocks base method.
func (m *MockOps) StreamCopy(ctx context.Context, src, dst backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCopy", ctx, src, dst, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCopy indicates an expected call of StreamCopy.
func (mr *MockOpsMockRecorder) StreamCopy(ctx, src, dst, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCopy", reflect.TypeOf((*MockOps)(nil).StreamCopy), ctx, src, dst, key)
}

// Usage mocks base method.
func (m *MockOps) Usage() *counter.UsageTracker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(*counter.UsageTracker)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *MockOpsMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockOps)(nil).Usage))
}

// WithTimeout mocks base method.
func (m *MockOps) WithTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockOpsMockRecorder) WithTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockOps)(nil).WithTimeout), ctx)
}

// MockCleanupDeps is a mock of CleanupDeps interface.
type MockCleanupDeps struct {
	ctrl     *gomock.Controller
	recorder *MockCleanupDepsMockRecorder
	isgomock struct{}
}

// MockCleanupDepsMockRecorder is the mock recorder for MockCleanupDeps.
type MockCleanupDepsMockRecorder struct {
	mock *MockCleanupDeps
}

// NewMockCleanupDeps creates a new mock instance.
func NewMockCleanupDeps(ctrl *gomock.Controller) *MockCleanupDeps {
	mock := &MockCleanupDeps{ctrl: ctrl}
	mock.recorder = &MockCleanupDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleanupDeps) EXPECT() *MockCleanupDepsMockRecorder {
	return m.recorder
}

// AcquireAdmission mocks base method.
func (m *MockCleanupDeps) AcquireAdmission(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAdmission", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcquireAdmission indicates an expected call of AcquireAdmission.
func (mr *MockCleanupDepsMockRecorder) AcquireAdmission(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAdmission", reflect.TypeOf((*MockCleanupDeps)(nil).AcquireAdmission), ctx)
}

// DeleteOrEnqueue mocks base method.
func (m *MockCleanupDeps) DeleteOrEnqueue(ctx context.Context, be backend.ObjectBackend, backendName, key, reason string, sizeBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrEnqueue", ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteOrEnqueue indicates an expected call of DeleteOrEnqueue.
func (mr *MockCleanupDepsMockRecorder) DeleteOrEnqueue(ctx, be, backendName, key, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrEnqueue", reflect.TypeOf((*MockCleanupDeps)(nil).DeleteOrEnqueue), ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteWithTimeout mocks base method.
func (m *MockCleanupDeps) DeleteWithTimeout(ctx context.Context, be backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeout", ctx, be, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTimeout indicates an expected call of DeleteWithTimeout.
func (mr *MockCleanupDepsMockRecorder) DeleteWithTimeout(ctx, be, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeout", reflect.TypeOf((*MockCleanupDeps)(nil).DeleteWithTimeout), ctx, be, key)
}

// GetBackend mocks base method.
func (m *MockCleanupDeps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockCleanupDepsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockCleanupDeps)(nil).GetBackend), name)
}

// ReleaseAdmission mocks base method.
func (m *MockCleanupDeps) ReleaseAdmission() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseAdmission")
}

// ReleaseAdmission indicates an expected call of ReleaseAdmission.
func (mr *MockCleanupDepsMockRecorder) ReleaseAdmission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAdmission", reflect.TypeOf((*MockCleanupDeps)(nil).ReleaseAdmission))
}

// Store mocks base method.
func (m *MockCleanupDeps) Store() store.MetadataStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(store.MetadataStore)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCleanupDepsMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCleanupDeps)(nil).Store))
}

// StreamCopy mocks base method.
func (m *MockCleanupDeps) StreamCopy(ctx context.Context, src, dst backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCopy", ctx, src, dst, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCopy indicates an expected call of StreamCopy.
func (mr *MockCleanupDepsMockRecorder) StreamCopy(ctx, src, dst, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCopy", reflect.TypeOf((*MockCleanupDeps)(nil).StreamCopy), ctx, src, dst, key)
}

// Usage mocks base method.
func (m *MockCleanupDeps) Usage() *counter.UsageTracker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(*counter.UsageTracker)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *MockCleanupDepsMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockCleanupDeps)(nil).Usage))
}

// WithTimeout mocks base method.
func (m *MockCleanupDeps) WithTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockCleanupDepsMockRecorder) WithTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockCleanupDeps)(nil).WithTimeout), ctx)
}

// MockScrubberDeps is a mock of ScrubberDeps interface.
type MockScrubberDeps struct {
	ctrl     *gomock.Controller
	recorder *MockScrubberDepsMockRecorder
	isgomock struct{}
}

// MockScrubberDepsMockRecorder is the mock recorder for MockScrubberDeps.
type MockScrubberDepsMockRecorder struct {
	mock *MockScrubberDeps
}

// NewMockScrubberDeps creates a new mock instance.
func NewMockScrubberDeps(ctrl *gomock.Controller) *MockScrubberDeps {
	mock := &MockScrubberDeps{ctrl: ctrl}
	mock.recorder = &MockScrubberDepsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrubberDeps) EXPECT() *MockScrubberDepsMockRecorder {
	return m.recorder
}

// DeleteOrEnqueue mocks base method.
func (m *MockScrubberDeps) DeleteOrEnqueue(ctx context.Context, be backend.ObjectBackend, backendName, key, reason string, sizeBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrEnqueue", ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteOrEnqueue indicates an expected call of DeleteOrEnqueue.
func (mr *MockScrubberDepsMockRecorder) DeleteOrEnqueue(ctx, be, backendName, key, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrEnqueue", reflect.TypeOf((*MockScrubberDeps)(nil).DeleteOrEnqueue), ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteWithTimeout mocks base method.
func (m *MockScrubberDeps) DeleteWithTimeout(ctx context.Context, be backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeout", ctx, be, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTimeout indicates an expected call of DeleteWithTimeout.
func (mr *MockScrubberDepsMockRecorder) DeleteWithTimeout(ctx, be, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeout", reflect.TypeOf((*MockScrubberDeps)(nil).DeleteWithTimeout), ctx, be, key)
}

// GetBackend mocks base method.
func (m *MockScrubberDeps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockScrubberDepsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockScrubberDeps)(nil).GetBackend), name)
}

// Store mocks base method.
func (m *MockScrubberDeps) Store() store.MetadataStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(store.MetadataStore)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockScrubberDepsMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockScrubberDeps)(nil).Store))
}

// StreamCopy mocks base method.
func (m *MockScrubberDeps) StreamCopy(ctx context.Context, src, dst backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCopy", ctx, src, dst, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCopy indicates an expected call of StreamCopy.
func (mr *MockScrubberDepsMockRecorder) StreamCopy(ctx, src, dst, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCopy", reflect.TypeOf((*MockScrubberDeps)(nil).StreamCopy), ctx, src, dst, key)
}

// Usage mocks base method.
func (m *MockScrubberDeps) Usage() *counter.UsageTracker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(*counter.UsageTracker)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *MockScrubberDepsMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockScrubberDeps)(nil).Usage))
}

// WithTimeout mocks base method.
func (m *MockScrubberDeps) WithTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockScrubberDepsMockRecorder) WithTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockScrubberDeps)(nil).WithTimeout), ctx)
}

// MockBackendSyncer is a mock of BackendSyncer interface.
type MockBackendSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockBackendSyncerMockRecorder
	isgomock struct{}
}

// MockBackendSyncerMockRecorder is the mock recorder for MockBackendSyncer.
type MockBackendSyncerMockRecorder struct {
	mock *MockBackendSyncer
}

// NewMockBackendSyncer creates a new mock instance.
func NewMockBackendSyncer(ctrl *gomock.Controller) *MockBackendSyncer {
	mock := &MockBackendSyncer{ctrl: ctrl}
	mock.recorder = &MockBackendSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendSyncer) EXPECT() *MockBackendSyncerMockRecorder {
	return m.recorder
}

// BackendOrder mocks base method.
func (m *MockBackendSyncer) BackendOrder() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendOrder")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BackendOrder indicates an expected call of BackendOrder.
func (mr *MockBackendSyncerMockRecorder) BackendOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendOrder", reflect.TypeOf((*MockBackendSyncer)(nil).BackendOrder))
}

// SyncBackend mocks base method.
func (m *MockBackendSyncer) SyncBackend(ctx context.Context, backendName, bucket string, knownBuckets []string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncBackend", ctx, backendName, bucket, knownBuckets)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SyncBackend indicates an expected call of SyncBackend.
func (mr *MockBackendSyncerMockRecorder) SyncBackend(ctx, backendName, bucket, knownBuckets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncBackend", reflect.TypeOf((*MockBackendSyncer)(nil).SyncBackend), ctx, backendName, bucket, knownBuckets)
}

// UpdateQuotaMetrics mocks base method.
func (m *MockBackendSyncer) UpdateQuotaMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotaMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuotaMetrics indicates an expected call of UpdateQuotaMetrics.
func (mr *MockBackendSyncerMockRecorder) UpdateQuotaMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotaMetrics", reflect.TypeOf((*MockBackendSyncer)(nil).UpdateQuotaMetrics), ctx)
}
