// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/worker (interfaces: Ops,CleanupOps,ScrubberOps,BackendSyncer)
//
// Generated by this command:
//
//	mockgen -destination=mock_ops_test.go -package=worker github.com/afreidah/s3-orchestrator/internal/worker Ops,CleanupOps,ScrubberOps,BackendSyncer
//

// Package worker is a generated GoMock package.
package worker

import (
	context "context"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	counter "github.com/afreidah/s3-orchestrator/internal/counter"
	accounting "github.com/afreidah/s3-orchestrator/internal/proxy/accounting"
	gomock "go.uber.org/mock/gomock"
)

// MockOps is a mock of Ops interface.
type MockOps struct {
	ctrl     *gomock.Controller
	recorder *MockOpsMockRecorder
	isgomock struct{}
}

// MockOpsMockRecorder is the mock recorder for MockOps.
type MockOpsMockRecorder struct {
	mock *MockOps
}

// NewMockOps creates a new mock instance.
func NewMockOps(ctrl *gomock.Controller) *MockOps {
	mock := &MockOps{ctrl: ctrl}
	mock.recorder = &MockOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOps) EXPECT() *MockOpsMockRecorder {
	return m.recorder
}

// Acct mocks base method.
func (m *MockOps) Acct() *accounting.Recorder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acct")
	ret0, _ := ret[0].(*accounting.Recorder)
	return ret0
}

// Acct indicates an expected call of Acct.
func (mr *MockOpsMockRecorder) Acct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acct", reflect.TypeOf((*MockOps)(nil).Acct))
}

// AcquireAdmission mocks base method.
func (m *MockOps) AcquireAdmission(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAdmission", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcquireAdmission indicates an expected call of AcquireAdmission.
func (mr *MockOpsMockRecorder) AcquireAdmission(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAdmission", reflect.TypeOf((*MockOps)(nil).AcquireAdmission), ctx)
}

// BackendOrder mocks base method.
func (m *MockOps) BackendOrder() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendOrder")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BackendOrder indicates an expected call of BackendOrder.
func (mr *MockOpsMockRecorder) BackendOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendOrder", reflect.TypeOf((*MockOps)(nil).BackendOrder))
}

// Backends mocks base method.
func (m *MockOps) Backends() map[string]backend.ObjectBackend {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backends")
	ret0, _ := ret[0].(map[string]backend.ObjectBackend)
	return ret0
}

// Backends indicates an expected call of Backends.
func (mr *MockOpsMockRecorder) Backends() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backends", reflect.TypeOf((*MockOps)(nil).Backends))
}

// DeleteOrEnqueue mocks base method.
func (m *MockOps) DeleteOrEnqueue(ctx context.Context, be backend.ObjectBackend, backendName, key, reason string, sizeBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrEnqueue", ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteOrEnqueue indicates an expected call of DeleteOrEnqueue.
func (mr *MockOpsMockRecorder) DeleteOrEnqueue(ctx, be, backendName, key, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrEnqueue", reflect.TypeOf((*MockOps)(nil).DeleteOrEnqueue), ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteWithTimeout mocks base method.
func (m *MockOps) DeleteWithTimeout(ctx context.Context, be backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeout", ctx, be, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTimeout indicates an expected call of DeleteWithTimeout.
func (mr *MockOpsMockRecorder) DeleteWithTimeout(ctx, be, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeout", reflect.TypeOf((*MockOps)(nil).DeleteWithTimeout), ctx, be, key)
}

// ExcludeDraining mocks base method.
func (m *MockOps) ExcludeDraining(eligible []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExcludeDraining", eligible)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ExcludeDraining indicates an expected call of ExcludeDraining.
func (mr *MockOpsMockRecorder) ExcludeDraining(eligible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExcludeDraining", reflect.TypeOf((*MockOps)(nil).ExcludeDraining), eligible)
}

// GetBackend mocks base method.
func (m *MockOps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockOpsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockOps)(nil).GetBackend), name)
}

// IsDraining mocks base method.
func (m *MockOps) IsDraining(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDraining", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDraining indicates an expected call of IsDraining.
func (mr *MockOpsMockRecorder) IsDraining(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDraining", reflect.TypeOf((*MockOps)(nil).IsDraining), name)
}

// ReleaseAdmission mocks base method.
func (m *MockOps) ReleaseAdmission() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseAdmission")
}

// ReleaseAdmission indicates an expected call of ReleaseAdmission.
func (mr *MockOpsMockRecorder) ReleaseAdmission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAdmission", reflect.TypeOf((*MockOps)(nil).ReleaseAdmission))
}

// SelectReplicaTarget mocks base method.
func (m *MockOps) SelectReplicaTarget(ctx context.Context, size int64, exclusion map[string]bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectReplicaTarget", ctx, size, exclusion)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectReplicaTarget indicates an expected call of SelectReplicaTarget.
func (mr *MockOpsMockRecorder) SelectReplicaTarget(ctx, size, exclusion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectReplicaTarget", reflect.TypeOf((*MockOps)(nil).SelectReplicaTarget), ctx, size, exclusion)
}

// StreamCopy mocks base method.
func (m *MockOps) StreamCopy(ctx context.Context, src, dst backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCopy", ctx, src, dst, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCopy indicates an expected call of StreamCopy.
func (mr *MockOpsMockRecorder) StreamCopy(ctx, src, dst, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCopy", reflect.TypeOf((*MockOps)(nil).StreamCopy), ctx, src, dst, key)
}

// Usage mocks base method.
func (m *MockOps) Usage() *counter.UsageTracker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(*counter.UsageTracker)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *MockOpsMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockOps)(nil).Usage))
}

// WithTimeout mocks base method.
func (m *MockOps) WithTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockOpsMockRecorder) WithTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockOps)(nil).WithTimeout), ctx)
}

// MockCleanupOps is a mock of CleanupOps interface.
type MockCleanupOps struct {
	ctrl     *gomock.Controller
	recorder *MockCleanupOpsMockRecorder
	isgomock struct{}
}

// MockCleanupOpsMockRecorder is the mock recorder for MockCleanupOps.
type MockCleanupOpsMockRecorder struct {
	mock *MockCleanupOps
}

// NewMockCleanupOps creates a new mock instance.
func NewMockCleanupOps(ctrl *gomock.Controller) *MockCleanupOps {
	mock := &MockCleanupOps{ctrl: ctrl}
	mock.recorder = &MockCleanupOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCleanupOps) EXPECT() *MockCleanupOpsMockRecorder {
	return m.recorder
}

// Acct mocks base method.
func (m *MockCleanupOps) Acct() *accounting.Recorder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acct")
	ret0, _ := ret[0].(*accounting.Recorder)
	return ret0
}

// Acct indicates an expected call of Acct.
func (mr *MockCleanupOpsMockRecorder) Acct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acct", reflect.TypeOf((*MockCleanupOps)(nil).Acct))
}

// AcquireAdmission mocks base method.
func (m *MockCleanupOps) AcquireAdmission(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireAdmission", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AcquireAdmission indicates an expected call of AcquireAdmission.
func (mr *MockCleanupOpsMockRecorder) AcquireAdmission(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireAdmission", reflect.TypeOf((*MockCleanupOps)(nil).AcquireAdmission), ctx)
}

// DeleteOrEnqueue mocks base method.
func (m *MockCleanupOps) DeleteOrEnqueue(ctx context.Context, be backend.ObjectBackend, backendName, key, reason string, sizeBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrEnqueue", ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteOrEnqueue indicates an expected call of DeleteOrEnqueue.
func (mr *MockCleanupOpsMockRecorder) DeleteOrEnqueue(ctx, be, backendName, key, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrEnqueue", reflect.TypeOf((*MockCleanupOps)(nil).DeleteOrEnqueue), ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteWithTimeout mocks base method.
func (m *MockCleanupOps) DeleteWithTimeout(ctx context.Context, be backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeout", ctx, be, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTimeout indicates an expected call of DeleteWithTimeout.
func (mr *MockCleanupOpsMockRecorder) DeleteWithTimeout(ctx, be, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeout", reflect.TypeOf((*MockCleanupOps)(nil).DeleteWithTimeout), ctx, be, key)
}

// GetBackend mocks base method.
func (m *MockCleanupOps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockCleanupOpsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockCleanupOps)(nil).GetBackend), name)
}

// ReleaseAdmission mocks base method.
func (m *MockCleanupOps) ReleaseAdmission() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseAdmission")
}

// ReleaseAdmission indicates an expected call of ReleaseAdmission.
func (mr *MockCleanupOpsMockRecorder) ReleaseAdmission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAdmission", reflect.TypeOf((*MockCleanupOps)(nil).ReleaseAdmission))
}

// StreamCopy mocks base method.
func (m *MockCleanupOps) StreamCopy(ctx context.Context, src, dst backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCopy", ctx, src, dst, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCopy indicates an expected call of StreamCopy.
func (mr *MockCleanupOpsMockRecorder) StreamCopy(ctx, src, dst, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCopy", reflect.TypeOf((*MockCleanupOps)(nil).StreamCopy), ctx, src, dst, key)
}

// Usage mocks base method.
func (m *MockCleanupOps) Usage() *counter.UsageTracker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(*counter.UsageTracker)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *MockCleanupOpsMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockCleanupOps)(nil).Usage))
}

// WithTimeout mocks base method.
func (m *MockCleanupOps) WithTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockCleanupOpsMockRecorder) WithTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockCleanupOps)(nil).WithTimeout), ctx)
}

// MockScrubberOps is a mock of ScrubberOps interface.
type MockScrubberOps struct {
	ctrl     *gomock.Controller
	recorder *MockScrubberOpsMockRecorder
	isgomock struct{}
}

// MockScrubberOpsMockRecorder is the mock recorder for MockScrubberOps.
type MockScrubberOpsMockRecorder struct {
	mock *MockScrubberOps
}

// NewMockScrubberOps creates a new mock instance.
func NewMockScrubberOps(ctrl *gomock.Controller) *MockScrubberOps {
	mock := &MockScrubberOps{ctrl: ctrl}
	mock.recorder = &MockScrubberOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrubberOps) EXPECT() *MockScrubberOpsMockRecorder {
	return m.recorder
}

// Acct mocks base method.
func (m *MockScrubberOps) Acct() *accounting.Recorder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acct")
	ret0, _ := ret[0].(*accounting.Recorder)
	return ret0
}

// Acct indicates an expected call of Acct.
func (mr *MockScrubberOpsMockRecorder) Acct() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acct", reflect.TypeOf((*MockScrubberOps)(nil).Acct))
}

// DeleteOrEnqueue mocks base method.
func (m *MockScrubberOps) DeleteOrEnqueue(ctx context.Context, be backend.ObjectBackend, backendName, key, reason string, sizeBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOrEnqueue", ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteOrEnqueue indicates an expected call of DeleteOrEnqueue.
func (mr *MockScrubberOpsMockRecorder) DeleteOrEnqueue(ctx, be, backendName, key, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrEnqueue", reflect.TypeOf((*MockScrubberOps)(nil).DeleteOrEnqueue), ctx, be, backendName, key, reason, sizeBytes)
}

// DeleteWithTimeout mocks base method.
func (m *MockScrubberOps) DeleteWithTimeout(ctx context.Context, be backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTimeout", ctx, be, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTimeout indicates an expected call of DeleteWithTimeout.
func (mr *MockScrubberOpsMockRecorder) DeleteWithTimeout(ctx, be, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTimeout", reflect.TypeOf((*MockScrubberOps)(nil).DeleteWithTimeout), ctx, be, key)
}

// GetBackend mocks base method.
func (m *MockScrubberOps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockScrubberOpsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockScrubberOps)(nil).GetBackend), name)
}

// StreamCopy mocks base method.
func (m *MockScrubberOps) StreamCopy(ctx context.Context, src, dst backend.ObjectBackend, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCopy", ctx, src, dst, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCopy indicates an expected call of StreamCopy.
func (mr *MockScrubberOpsMockRecorder) StreamCopy(ctx, src, dst, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCopy", reflect.TypeOf((*MockScrubberOps)(nil).StreamCopy), ctx, src, dst, key)
}

// Usage mocks base method.
func (m *MockScrubberOps) Usage() *counter.UsageTracker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage")
	ret0, _ := ret[0].(*counter.UsageTracker)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *MockScrubberOpsMockRecorder) Usage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockScrubberOps)(nil).Usage))
}

// WithTimeout mocks base method.
func (m *MockScrubberOps) WithTimeout(ctx context.Context) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MockScrubberOpsMockRecorder) WithTimeout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MockScrubberOps)(nil).WithTimeout), ctx)
}

// MockBackendSyncer is a mock of BackendSyncer interface.
type MockBackendSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockBackendSyncerMockRecorder
	isgomock struct{}
}

// MockBackendSyncerMockRecorder is the mock recorder for MockBackendSyncer.
type MockBackendSyncerMockRecorder struct {
	mock *MockBackendSyncer
}

// NewMockBackendSyncer creates a new mock instance.
func NewMockBackendSyncer(ctrl *gomock.Controller) *MockBackendSyncer {
	mock := &MockBackendSyncer{ctrl: ctrl}
	mock.recorder = &MockBackendSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendSyncer) EXPECT() *MockBackendSyncerMockRecorder {
	return m.recorder
}

// BackendOrder mocks base method.
func (m *MockBackendSyncer) BackendOrder() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendOrder")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BackendOrder indicates an expected call of BackendOrder.
func (mr *MockBackendSyncerMockRecorder) BackendOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendOrder", reflect.TypeOf((*MockBackendSyncer)(nil).BackendOrder))
}

// ReconcileBackend mocks base method.
func (m *MockBackendSyncer) ReconcileBackend(ctx context.Context, backendName, bucket string, knownBuckets []string) (*ReconcileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileBackend", ctx, backendName, bucket, knownBuckets)
	ret0, _ := ret[0].(*ReconcileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileBackend indicates an expected call of ReconcileBackend.
func (mr *MockBackendSyncerMockRecorder) ReconcileBackend(ctx, backendName, bucket, knownBuckets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileBackend", reflect.TypeOf((*MockBackendSyncer)(nil).ReconcileBackend), ctx, backendName, bucket, knownBuckets)
}

// SyncBackend mocks base method.
func (m *MockBackendSyncer) SyncBackend(ctx context.Context, backendName, bucket string, knownBuckets []string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncBackend", ctx, backendName, bucket, knownBuckets)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SyncBackend indicates an expected call of SyncBackend.
func (mr *MockBackendSyncerMockRecorder) SyncBackend(ctx, backendName, bucket, knownBuckets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncBackend", reflect.TypeOf((*MockBackendSyncer)(nil).SyncBackend), ctx, backendName, bucket, knownBuckets)
}

// UpdateQuotaMetrics mocks base method.
func (m *MockBackendSyncer) UpdateQuotaMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotaMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuotaMetrics indicates an expected call of UpdateQuotaMetrics.
func (mr *MockBackendSyncerMockRecorder) UpdateQuotaMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotaMetrics", reflect.TypeOf((*MockBackendSyncer)(nil).UpdateQuotaMetrics), ctx)
}
