// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/transport/admin (interfaces: BackendOps,DashboardReader,RuntimeOps,ReplicatorOps,RebalancerOps,OverReplicationOps,ScrubberOps,Reconciler)
//
// Generated by this command:
//
//	mockgen -destination=mock_deps_test.go -package=admin github.com/afreidah/s3-orchestrator/internal/transport/admin BackendOps,DashboardReader,RuntimeOps,ReplicatorOps,RebalancerOps,OverReplicationOps,ScrubberOps,Reconciler
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	reflect "reflect"

	backend "github.com/afreidah/s3-orchestrator/internal/backend"
	config "github.com/afreidah/s3-orchestrator/internal/config"
	progress "github.com/afreidah/s3-orchestrator/internal/progress"
	dashboard "github.com/afreidah/s3-orchestrator/internal/proxy/dashboard"
	worker "github.com/afreidah/s3-orchestrator/internal/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockBackendOps is a mock of BackendOps interface.
type MockBackendOps struct {
	ctrl     *gomock.Controller
	recorder *MockBackendOpsMockRecorder
	isgomock struct{}
}

// MockBackendOpsMockRecorder is the mock recorder for MockBackendOps.
type MockBackendOpsMockRecorder struct {
	mock *MockBackendOps
}

// NewMockBackendOps creates a new mock instance.
func NewMockBackendOps(ctrl *gomock.Controller) *MockBackendOps {
	mock := &MockBackendOps{ctrl: ctrl}
	mock.recorder = &MockBackendOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendOps) EXPECT() *MockBackendOpsMockRecorder {
	return m.recorder
}

// FlushUsage mocks base method.
func (m *MockBackendOps) FlushUsage(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushUsage", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushUsage indicates an expected call of FlushUsage.
func (mr *MockBackendOpsMockRecorder) FlushUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushUsage", reflect.TypeOf((*MockBackendOps)(nil).FlushUsage), ctx)
}

// IntegrityConfig mocks base method.
func (m *MockBackendOps) IntegrityConfig() *config.IntegrityConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntegrityConfig")
	ret0, _ := ret[0].(*config.IntegrityConfig)
	return ret0
}

// IntegrityConfig indicates an expected call of IntegrityConfig.
func (mr *MockBackendOpsMockRecorder) IntegrityConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntegrityConfig", reflect.TypeOf((*MockBackendOps)(nil).IntegrityConfig))
}

// ReconcileUsage mocks base method.
func (m *MockBackendOps) ReconcileUsage(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileUsage", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileUsage indicates an expected call of ReconcileUsage.
func (mr *MockBackendOpsMockRecorder) ReconcileUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileUsage", reflect.TypeOf((*MockBackendOps)(nil).ReconcileUsage), ctx)
}

// RecordUsage mocks base method.
func (m *MockBackendOps) RecordUsage(backendName string, requests, ingressBytes, egressBytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUsage", backendName, requests, ingressBytes, egressBytes)
}

// RecordUsage indicates an expected call of RecordUsage.
func (mr *MockBackendOpsMockRecorder) RecordUsage(backendName, requests, ingressBytes, egressBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUsage", reflect.TypeOf((*MockBackendOps)(nil).RecordUsage), backendName, requests, ingressBytes, egressBytes)
}

// MockDashboardReader is a mock of DashboardReader interface.
type MockDashboardReader struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardReaderMockRecorder
	isgomock struct{}
}

// MockDashboardReaderMockRecorder is the mock recorder for MockDashboardReader.
type MockDashboardReaderMockRecorder struct {
	mock *MockDashboardReader
}

// NewMockDashboardReader creates a new mock instance.
func NewMockDashboardReader(ctrl *gomock.Controller) *MockDashboardReader {
	mock := &MockDashboardReader{ctrl: ctrl}
	mock.recorder = &MockDashboardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardReader) EXPECT() *MockDashboardReaderMockRecorder {
	return m.recorder
}

// GetData mocks base method.
func (m *MockDashboardReader) GetData(ctx context.Context) (*dashboard.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", ctx)
	ret0, _ := ret[0].(*dashboard.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockDashboardReaderMockRecorder) GetData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockDashboardReader)(nil).GetData), ctx)
}

// MockRuntimeOps is a mock of RuntimeOps interface.
type MockRuntimeOps struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeOpsMockRecorder
	isgomock struct{}
}

// MockRuntimeOpsMockRecorder is the mock recorder for MockRuntimeOps.
type MockRuntimeOpsMockRecorder struct {
	mock *MockRuntimeOps
}

// NewMockRuntimeOps creates a new mock instance.
func NewMockRuntimeOps(ctrl *gomock.Controller) *MockRuntimeOps {
	mock := &MockRuntimeOps{ctrl: ctrl}
	mock.recorder = &MockRuntimeOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeOps) EXPECT() *MockRuntimeOpsMockRecorder {
	return m.recorder
}

// GetBackend mocks base method.
func (m *MockRuntimeOps) GetBackend(name string) (backend.ObjectBackend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackend", name)
	ret0, _ := ret[0].(backend.ObjectBackend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackend indicates an expected call of GetBackend.
func (mr *MockRuntimeOpsMockRecorder) GetBackend(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackend", reflect.TypeOf((*MockRuntimeOps)(nil).GetBackend), name)
}

// UpdateQuotaMetrics mocks base method.
func (m *MockRuntimeOps) UpdateQuotaMetrics(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotaMetrics", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuotaMetrics indicates an expected call of UpdateQuotaMetrics.
func (mr *MockRuntimeOpsMockRecorder) UpdateQuotaMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotaMetrics", reflect.TypeOf((*MockRuntimeOps)(nil).UpdateQuotaMetrics), ctx)
}

// MockReplicatorOps is a mock of ReplicatorOps interface.
type MockReplicatorOps struct {
	ctrl     *gomock.Controller
	recorder *MockReplicatorOpsMockRecorder
	isgomock struct{}
}

// MockReplicatorOpsMockRecorder is the mock recorder for MockReplicatorOps.
type MockReplicatorOpsMockRecorder struct {
	mock *MockReplicatorOps
}

// NewMockReplicatorOps creates a new mock instance.
func NewMockReplicatorOps(ctrl *gomock.Controller) *MockReplicatorOps {
	mock := &MockReplicatorOps{ctrl: ctrl}
	mock.recorder = &MockReplicatorOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplicatorOps) EXPECT() *MockReplicatorOpsMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockReplicatorOps) Config() *config.ReplicationConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.ReplicationConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockReplicatorOpsMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockReplicatorOps)(nil).Config))
}

// Replicate mocks base method.
func (m *MockReplicatorOps) Replicate(ctx context.Context, cfg config.ReplicationConfig, observer progress.Observer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replicate", ctx, cfg, observer)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replicate indicates an expected call of Replicate.
func (mr *MockReplicatorOpsMockRecorder) Replicate(ctx, cfg, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replicate", reflect.TypeOf((*MockReplicatorOps)(nil).Replicate), ctx, cfg, observer)
}

// MockRebalancerOps is a mock of RebalancerOps interface.
type MockRebalancerOps struct {
	ctrl     *gomock.Controller
	recorder *MockRebalancerOpsMockRecorder
	isgomock struct{}
}

// MockRebalancerOpsMockRecorder is the mock recorder for MockRebalancerOps.
type MockRebalancerOpsMockRecorder struct {
	mock *MockRebalancerOps
}

// NewMockRebalancerOps creates a new mock instance.
func NewMockRebalancerOps(ctrl *gomock.Controller) *MockRebalancerOps {
	mock := &MockRebalancerOps{ctrl: ctrl}
	mock.recorder = &MockRebalancerOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRebalancerOps) EXPECT() *MockRebalancerOpsMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockRebalancerOps) Config() *config.RebalanceConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.RebalanceConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockRebalancerOpsMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockRebalancerOps)(nil).Config))
}

// Rebalance mocks base method.
func (m *MockRebalancerOps) Rebalance(ctx context.Context, cfg config.RebalanceConfig, observer progress.Observer) (worker.RebalanceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebalance", ctx, cfg, observer)
	ret0, _ := ret[0].(worker.RebalanceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rebalance indicates an expected call of Rebalance.
func (mr *MockRebalancerOpsMockRecorder) Rebalance(ctx, cfg, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebalance", reflect.TypeOf((*MockRebalancerOps)(nil).Rebalance), ctx, cfg, observer)
}

// MockOverReplicationOps is a mock of OverReplicationOps interface.
type MockOverReplicationOps struct {
	ctrl     *gomock.Controller
	recorder *MockOverReplicationOpsMockRecorder
	isgomock struct{}
}

// MockOverReplicationOpsMockRecorder is the mock recorder for MockOverReplicationOps.
type MockOverReplicationOpsMockRecorder struct {
	mock *MockOverReplicationOps
}

// NewMockOverReplicationOps creates a new mock instance.
func NewMockOverReplicationOps(ctrl *gomock.Controller) *MockOverReplicationOps {
	mock := &MockOverReplicationOps{ctrl: ctrl}
	mock.recorder = &MockOverReplicationOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOverReplicationOps) EXPECT() *MockOverReplicationOpsMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockOverReplicationOps) Clean(ctx context.Context, cfg config.ReplicationConfig, observer progress.Observer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, cfg, observer)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockOverReplicationOpsMockRecorder) Clean(ctx, cfg, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockOverReplicationOps)(nil).Clean), ctx, cfg, observer)
}

// Config mocks base method.
func (m *MockOverReplicationOps) Config() *config.ReplicationConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.ReplicationConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockOverReplicationOpsMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockOverReplicationOps)(nil).Config))
}

// CountPending mocks base method.
func (m *MockOverReplicationOps) CountPending(ctx context.Context, factor int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPending", ctx, factor)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPending indicates an expected call of CountPending.
func (mr *MockOverReplicationOpsMockRecorder) CountPending(ctx, factor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPending", reflect.TypeOf((*MockOverReplicationOps)(nil).CountPending), ctx, factor)
}

// MockScrubberOps is a mock of ScrubberOps interface.
type MockScrubberOps struct {
	ctrl     *gomock.Controller
	recorder *MockScrubberOpsMockRecorder
	isgomock struct{}
}

// MockScrubberOpsMockRecorder is the mock recorder for MockScrubberOps.
type MockScrubberOpsMockRecorder struct {
	mock *MockScrubberOps
}

// NewMockScrubberOps creates a new mock instance.
func NewMockScrubberOps(ctrl *gomock.Controller) *MockScrubberOps {
	mock := &MockScrubberOps{ctrl: ctrl}
	mock.recorder = &MockScrubberOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrubberOps) EXPECT() *MockScrubberOpsMockRecorder {
	return m.recorder
}

// Backfill mocks base method.
func (m *MockScrubberOps) Backfill(ctx context.Context, batchSize, offset int, observer progress.Observer) (worker.WorkSummary, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backfill", ctx, batchSize, offset, observer)
	ret0, _ := ret[0].(worker.WorkSummary)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Backfill indicates an expected call of Backfill.
func (mr *MockScrubberOpsMockRecorder) Backfill(ctx, batchSize, offset, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backfill", reflect.TypeOf((*MockScrubberOps)(nil).Backfill), ctx, batchSize, offset, observer)
}

// Scrub mocks base method.
func (m *MockScrubberOps) Scrub(ctx context.Context, batchSize int, observer progress.Observer) worker.WorkSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrub", ctx, batchSize, observer)
	ret0, _ := ret[0].(worker.WorkSummary)
	return ret0
}

// Scrub indicates an expected call of Scrub.
func (mr *MockScrubberOpsMockRecorder) Scrub(ctx, batchSize, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrub", reflect.TypeOf((*MockScrubberOps)(nil).Scrub), ctx, batchSize, observer)
}

// MockReconciler is a mock of Reconciler interface.
type MockReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockReconcilerMockRecorder
	isgomock struct{}
}

// MockReconcilerMockRecorder is the mock recorder for MockReconciler.
type MockReconcilerMockRecorder struct {
	mock *MockReconciler
}

// NewMockReconciler creates a new mock instance.
func NewMockReconciler(ctrl *gomock.Controller) *MockReconciler {
	mock := &MockReconciler{ctrl: ctrl}
	mock.recorder = &MockReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciler) EXPECT() *MockReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockReconciler) Reconcile(ctx context.Context, backendName string) (*worker.ReconcileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, backendName)
	ret0, _ := ret[0].(*worker.ReconcileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockReconcilerMockRecorder) Reconcile(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockReconciler)(nil).Reconcile), ctx, backendName)
}

// ReconcileStreaming mocks base method.
func (m *MockReconciler) ReconcileStreaming(ctx context.Context, backendName string, observer progress.Observer) (*worker.ReconcileResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileStreaming", ctx, backendName, observer)
	ret0, _ := ret[0].(*worker.ReconcileResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileStreaming indicates an expected call of ReconcileStreaming.
func (mr *MockReconcilerMockRecorder) ReconcileStreaming(ctx, backendName, observer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileStreaming", reflect.TypeOf((*MockReconciler)(nil).ReconcileStreaming), ctx, backendName, observer)
}
