// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/s3-orchestrator/internal/store (interfaces: MetadataStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_generated_test.go -package=store github.com/afreidah/s3-orchestrator/internal/store MetadataStore
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMetadataStore is a mock of MetadataStore interface.
type MockMetadataStore struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataStoreMockRecorder
	isgomock struct{}
}

// MockMetadataStoreMockRecorder is the mock recorder for MockMetadataStore.
type MockMetadataStoreMockRecorder struct {
	mock *MockMetadataStore
}

// NewMockMetadataStore creates a new mock instance.
func NewMockMetadataStore(ctrl *gomock.Controller) *MockMetadataStore {
	mock := &MockMetadataStore{ctrl: ctrl}
	mock.recorder = &MockMetadataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataStore) EXPECT() *MockMetadataStoreMockRecorder {
	return m.recorder
}

// BackendObjectStats mocks base method.
func (m *MockMetadataStore) BackendObjectStats(ctx context.Context, backendName string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackendObjectStats", ctx, backendName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BackendObjectStats indicates an expected call of BackendObjectStats.
func (mr *MockMetadataStoreMockRecorder) BackendObjectStats(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackendObjectStats", reflect.TypeOf((*MockMetadataStore)(nil).BackendObjectStats), ctx, backendName)
}

// CleanupQueueDepth mocks base method.
func (m *MockMetadataStore) CleanupQueueDepth(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupQueueDepth", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupQueueDepth indicates an expected call of CleanupQueueDepth.
func (mr *MockMetadataStoreMockRecorder) CleanupQueueDepth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupQueueDepth", reflect.TypeOf((*MockMetadataStore)(nil).CleanupQueueDepth), ctx)
}

// CompleteCleanupItem mocks base method.
func (m *MockMetadataStore) CompleteCleanupItem(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCleanupItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteCleanupItem indicates an expected call of CompleteCleanupItem.
func (mr *MockMetadataStoreMockRecorder) CompleteCleanupItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCleanupItem", reflect.TypeOf((*MockMetadataStore)(nil).CompleteCleanupItem), ctx, id)
}

// CountOverReplicatedObjects mocks base method.
func (m *MockMetadataStore) CountOverReplicatedObjects(ctx context.Context, factor int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOverReplicatedObjects", ctx, factor)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOverReplicatedObjects indicates an expected call of CountOverReplicatedObjects.
func (mr *MockMetadataStoreMockRecorder) CountOverReplicatedObjects(ctx, factor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOverReplicatedObjects", reflect.TypeOf((*MockMetadataStore)(nil).CountOverReplicatedObjects), ctx, factor)
}

// CreateMultipartUpload mocks base method.
func (m *MockMetadataStore) CreateMultipartUpload(ctx context.Context, uploadID, key, backend, contentType string, metadata map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, uploadID, key, backend, contentType, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockMetadataStoreMockRecorder) CreateMultipartUpload(ctx, uploadID, key, backend, contentType, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockMetadataStore)(nil).CreateMultipartUpload), ctx, uploadID, key, backend, contentType, metadata)
}

// DecrementOrphanBytes mocks base method.
func (m *MockMetadataStore) DecrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOrphanBytes indicates an expected call of DecrementOrphanBytes.
func (mr *MockMetadataStoreMockRecorder) DecrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOrphanBytes", reflect.TypeOf((*MockMetadataStore)(nil).DecrementOrphanBytes), ctx, backendName, amount)
}

// DeleteBackendData mocks base method.
func (m *MockMetadataStore) DeleteBackendData(ctx context.Context, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackendData", ctx, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackendData indicates an expected call of DeleteBackendData.
func (mr *MockMetadataStoreMockRecorder) DeleteBackendData(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackendData", reflect.TypeOf((*MockMetadataStore)(nil).DeleteBackendData), ctx, backendName)
}

// DeleteMultipartUpload mocks base method.
func (m *MockMetadataStore) DeleteMultipartUpload(ctx context.Context, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultipartUpload", ctx, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultipartUpload indicates an expected call of DeleteMultipartUpload.
func (mr *MockMetadataStoreMockRecorder) DeleteMultipartUpload(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultipartUpload", reflect.TypeOf((*MockMetadataStore)(nil).DeleteMultipartUpload), ctx, uploadID)
}

// DeleteObject mocks base method.
func (m *MockMetadataStore) DeleteObject(ctx context.Context, key string) ([]DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key)
	ret0, _ := ret[0].([]DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockMetadataStoreMockRecorder) DeleteObject(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockMetadataStore)(nil).DeleteObject), ctx, key)
}

// DeleteObjectLocation mocks base method.
func (m *MockMetadataStore) DeleteObjectLocation(ctx context.Context, key, backendName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectLocation", ctx, key, backendName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectLocation indicates an expected call of DeleteObjectLocation.
func (mr *MockMetadataStoreMockRecorder) DeleteObjectLocation(ctx, key, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectLocation", reflect.TypeOf((*MockMetadataStore)(nil).DeleteObjectLocation), ctx, key, backendName)
}

// EnqueueCleanup mocks base method.
func (m *MockMetadataStore) EnqueueCleanup(ctx context.Context, backendName, objectKey, reason string, sizeBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueCleanup", ctx, backendName, objectKey, reason, sizeBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueCleanup indicates an expected call of EnqueueCleanup.
func (mr *MockMetadataStoreMockRecorder) EnqueueCleanup(ctx, backendName, objectKey, reason, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueCleanup", reflect.TypeOf((*MockMetadataStore)(nil).EnqueueCleanup), ctx, backendName, objectKey, reason, sizeBytes)
}

// FlushUsageDeltas mocks base method.
func (m *MockMetadataStore) FlushUsageDeltas(ctx context.Context, backendName, period string, apiRequests, egressBytes, ingressBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushUsageDeltas", ctx, backendName, period, apiRequests, egressBytes, ingressBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushUsageDeltas indicates an expected call of FlushUsageDeltas.
func (mr *MockMetadataStoreMockRecorder) FlushUsageDeltas(ctx, backendName, period, apiRequests, egressBytes, ingressBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushUsageDeltas", reflect.TypeOf((*MockMetadataStore)(nil).FlushUsageDeltas), ctx, backendName, period, apiRequests, egressBytes, ingressBytes)
}

// GetActiveMultipartCounts mocks base method.
func (m *MockMetadataStore) GetActiveMultipartCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMultipartCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMultipartCounts indicates an expected call of GetActiveMultipartCounts.
func (mr *MockMetadataStoreMockRecorder) GetActiveMultipartCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMultipartCounts", reflect.TypeOf((*MockMetadataStore)(nil).GetActiveMultipartCounts), ctx)
}

// GetAllObjectLocations mocks base method.
func (m *MockMetadataStore) GetAllObjectLocations(ctx context.Context, key string) ([]ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllObjectLocations", ctx, key)
	ret0, _ := ret[0].([]ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllObjectLocations indicates an expected call of GetAllObjectLocations.
func (mr *MockMetadataStoreMockRecorder) GetAllObjectLocations(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllObjectLocations", reflect.TypeOf((*MockMetadataStore)(nil).GetAllObjectLocations), ctx, key)
}

// GetBackendWithSpace mocks base method.
func (m *MockMetadataStore) GetBackendWithSpace(ctx context.Context, size int64, backendOrder []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackendWithSpace", ctx, size, backendOrder)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackendWithSpace indicates an expected call of GetBackendWithSpace.
func (mr *MockMetadataStoreMockRecorder) GetBackendWithSpace(ctx, size, backendOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackendWithSpace", reflect.TypeOf((*MockMetadataStore)(nil).GetBackendWithSpace), ctx, size, backendOrder)
}

// GetLeastUtilizedBackend mocks base method.
func (m *MockMetadataStore) GetLeastUtilizedBackend(ctx context.Context, size int64, eligible []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeastUtilizedBackend", ctx, size, eligible)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeastUtilizedBackend indicates an expected call of GetLeastUtilizedBackend.
func (mr *MockMetadataStoreMockRecorder) GetLeastUtilizedBackend(ctx, size, eligible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeastUtilizedBackend", reflect.TypeOf((*MockMetadataStore)(nil).GetLeastUtilizedBackend), ctx, size, eligible)
}

// GetMultipartUpload mocks base method.
func (m *MockMetadataStore) GetMultipartUpload(ctx context.Context, uploadID string) (*MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMultipartUpload", ctx, uploadID)
	ret0, _ := ret[0].(*MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMultipartUpload indicates an expected call of GetMultipartUpload.
func (mr *MockMetadataStoreMockRecorder) GetMultipartUpload(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMultipartUpload", reflect.TypeOf((*MockMetadataStore)(nil).GetMultipartUpload), ctx, uploadID)
}

// GetMultipartUploadsByBackend mocks base method.
func (m *MockMetadataStore) GetMultipartUploadsByBackend(ctx context.Context, backendName string) ([]MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMultipartUploadsByBackend", ctx, backendName)
	ret0, _ := ret[0].([]MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMultipartUploadsByBackend indicates an expected call of GetMultipartUploadsByBackend.
func (mr *MockMetadataStoreMockRecorder) GetMultipartUploadsByBackend(ctx, backendName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMultipartUploadsByBackend", reflect.TypeOf((*MockMetadataStore)(nil).GetMultipartUploadsByBackend), ctx, backendName)
}

// GetObjectCounts mocks base method.
func (m *MockMetadataStore) GetObjectCounts(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectCounts", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectCounts indicates an expected call of GetObjectCounts.
func (mr *MockMetadataStoreMockRecorder) GetObjectCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectCounts", reflect.TypeOf((*MockMetadataStore)(nil).GetObjectCounts), ctx)
}

// GetOverReplicatedObjects mocks base method.
func (m *MockMetadataStore) GetOverReplicatedObjects(ctx context.Context, factor, limit int) ([]ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverReplicatedObjects", ctx, factor, limit)
	ret0, _ := ret[0].([]ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverReplicatedObjects indicates an expected call of GetOverReplicatedObjects.
func (mr *MockMetadataStoreMockRecorder) GetOverReplicatedObjects(ctx, factor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverReplicatedObjects", reflect.TypeOf((*MockMetadataStore)(nil).GetOverReplicatedObjects), ctx, factor, limit)
}

// GetParts mocks base method.
func (m *MockMetadataStore) GetParts(ctx context.Context, uploadID string) ([]MultipartPart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParts", ctx, uploadID)
	ret0, _ := ret[0].([]MultipartPart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParts indicates an expected call of GetParts.
func (mr *MockMetadataStoreMockRecorder) GetParts(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParts", reflect.TypeOf((*MockMetadataStore)(nil).GetParts), ctx, uploadID)
}

// GetPendingCleanups mocks base method.
func (m *MockMetadataStore) GetPendingCleanups(ctx context.Context, limit int) ([]CleanupItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingCleanups", ctx, limit)
	ret0, _ := ret[0].([]CleanupItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingCleanups indicates an expected call of GetPendingCleanups.
func (mr *MockMetadataStoreMockRecorder) GetPendingCleanups(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingCleanups", reflect.TypeOf((*MockMetadataStore)(nil).GetPendingCleanups), ctx, limit)
}

// GetQuotaStats mocks base method.
func (m *MockMetadataStore) GetQuotaStats(ctx context.Context) (map[string]QuotaStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotaStats", ctx)
	ret0, _ := ret[0].(map[string]QuotaStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotaStats indicates an expected call of GetQuotaStats.
func (mr *MockMetadataStoreMockRecorder) GetQuotaStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotaStats", reflect.TypeOf((*MockMetadataStore)(nil).GetQuotaStats), ctx)
}

// GetStaleMultipartUploads mocks base method.
func (m *MockMetadataStore) GetStaleMultipartUploads(ctx context.Context, olderThan time.Duration) ([]MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaleMultipartUploads", ctx, olderThan)
	ret0, _ := ret[0].([]MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaleMultipartUploads indicates an expected call of GetStaleMultipartUploads.
func (mr *MockMetadataStoreMockRecorder) GetStaleMultipartUploads(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaleMultipartUploads", reflect.TypeOf((*MockMetadataStore)(nil).GetStaleMultipartUploads), ctx, olderThan)
}

// GetUnderReplicatedObjects mocks base method.
func (m *MockMetadataStore) GetUnderReplicatedObjects(ctx context.Context, factor, limit int) ([]ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnderReplicatedObjects", ctx, factor, limit)
	ret0, _ := ret[0].([]ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnderReplicatedObjects indicates an expected call of GetUnderReplicatedObjects.
func (mr *MockMetadataStoreMockRecorder) GetUnderReplicatedObjects(ctx, factor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnderReplicatedObjects", reflect.TypeOf((*MockMetadataStore)(nil).GetUnderReplicatedObjects), ctx, factor, limit)
}

// GetUnderReplicatedObjectsExcluding mocks base method.
func (m *MockMetadataStore) GetUnderReplicatedObjectsExcluding(ctx context.Context, factor, limit int, excludedBackends []string) ([]ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnderReplicatedObjectsExcluding", ctx, factor, limit, excludedBackends)
	ret0, _ := ret[0].([]ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnderReplicatedObjectsExcluding indicates an expected call of GetUnderReplicatedObjectsExcluding.
func (mr *MockMetadataStoreMockRecorder) GetUnderReplicatedObjectsExcluding(ctx, factor, limit, excludedBackends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnderReplicatedObjectsExcluding", reflect.TypeOf((*MockMetadataStore)(nil).GetUnderReplicatedObjectsExcluding), ctx, factor, limit, excludedBackends)
}

// GetUsageForPeriod mocks base method.
func (m *MockMetadataStore) GetUsageForPeriod(ctx context.Context, period string) (map[string]UsageStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsageForPeriod", ctx, period)
	ret0, _ := ret[0].(map[string]UsageStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsageForPeriod indicates an expected call of GetUsageForPeriod.
func (mr *MockMetadataStoreMockRecorder) GetUsageForPeriod(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsageForPeriod", reflect.TypeOf((*MockMetadataStore)(nil).GetUsageForPeriod), ctx, period)
}

// ImportObject mocks base method.
func (m *MockMetadataStore) ImportObject(ctx context.Context, key, backend string, size int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", ctx, key, backend, size)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockMetadataStoreMockRecorder) ImportObject(ctx, key, backend, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockMetadataStore)(nil).ImportObject), ctx, key, backend, size)
}

// IncrementOrphanBytes mocks base method.
func (m *MockMetadataStore) IncrementOrphanBytes(ctx context.Context, backendName string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOrphanBytes", ctx, backendName, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOrphanBytes indicates an expected call of IncrementOrphanBytes.
func (mr *MockMetadataStoreMockRecorder) IncrementOrphanBytes(ctx, backendName, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOrphanBytes", reflect.TypeOf((*MockMetadataStore)(nil).IncrementOrphanBytes), ctx, backendName, amount)
}

// ListDirectoryChildren mocks base method.
func (m *MockMetadataStore) ListDirectoryChildren(ctx context.Context, prefix, startAfter string, maxKeys int) (*DirectoryListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDirectoryChildren", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*DirectoryListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDirectoryChildren indicates an expected call of ListDirectoryChildren.
func (mr *MockMetadataStoreMockRecorder) ListDirectoryChildren(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDirectoryChildren", reflect.TypeOf((*MockMetadataStore)(nil).ListDirectoryChildren), ctx, prefix, startAfter, maxKeys)
}

// ListExpiredObjects mocks base method.
func (m *MockMetadataStore) ListExpiredObjects(ctx context.Context, prefix string, cutoff time.Time, limit int) ([]ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredObjects", ctx, prefix, cutoff, limit)
	ret0, _ := ret[0].([]ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredObjects indicates an expected call of ListExpiredObjects.
func (mr *MockMetadataStoreMockRecorder) ListExpiredObjects(ctx, prefix, cutoff, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredObjects", reflect.TypeOf((*MockMetadataStore)(nil).ListExpiredObjects), ctx, prefix, cutoff, limit)
}

// ListMultipartUploads mocks base method.
func (m *MockMetadataStore) ListMultipartUploads(ctx context.Context, prefix string, maxUploads int) ([]MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMultipartUploads", ctx, prefix, maxUploads)
	ret0, _ := ret[0].([]MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockMetadataStoreMockRecorder) ListMultipartUploads(ctx, prefix, maxUploads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMultipartUploads", reflect.TypeOf((*MockMetadataStore)(nil).ListMultipartUploads), ctx, prefix, maxUploads)
}

// ListObjects mocks base method.
func (m *MockMetadataStore) ListObjects(ctx context.Context, prefix, startAfter string, maxKeys int) (*ListObjectsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, startAfter, maxKeys)
	ret0, _ := ret[0].(*ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockMetadataStoreMockRecorder) ListObjects(ctx, prefix, startAfter, maxKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockMetadataStore)(nil).ListObjects), ctx, prefix, startAfter, maxKeys)
}

// ListObjectsByBackend mocks base method.
func (m *MockMetadataStore) ListObjectsByBackend(ctx context.Context, backendName string, limit int) ([]ObjectLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsByBackend", ctx, backendName, limit)
	ret0, _ := ret[0].([]ObjectLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsByBackend indicates an expected call of ListObjectsByBackend.
func (mr *MockMetadataStoreMockRecorder) ListObjectsByBackend(ctx, backendName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsByBackend", reflect.TypeOf((*MockMetadataStore)(nil).ListObjectsByBackend), ctx, backendName, limit)
}

// MoveObjectLocation mocks base method.
func (m *MockMetadataStore) MoveObjectLocation(ctx context.Context, key, fromBackend, toBackend string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveObjectLocation", ctx, key, fromBackend, toBackend)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveObjectLocation indicates an expected call of MoveObjectLocation.
func (mr *MockMetadataStoreMockRecorder) MoveObjectLocation(ctx, key, fromBackend, toBackend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObjectLocation", reflect.TypeOf((*MockMetadataStore)(nil).MoveObjectLocation), ctx, key, fromBackend, toBackend)
}

// RecordObject mocks base method.
func (m *MockMetadataStore) RecordObject(ctx context.Context, key, backend string, size int64, enc *EncryptionMeta) ([]DeletedCopy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordObject", ctx, key, backend, size, enc)
	ret0, _ := ret[0].([]DeletedCopy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordObject indicates an expected call of RecordObject.
func (mr *MockMetadataStoreMockRecorder) RecordObject(ctx, key, backend, size, enc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordObject", reflect.TypeOf((*MockMetadataStore)(nil).RecordObject), ctx, key, backend, size, enc)
}

// RecordPart mocks base method.
func (m *MockMetadataStore) RecordPart(ctx context.Context, uploadID string, partNumber int, etag string, size int64, enc *EncryptionMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPart", ctx, uploadID, partNumber, etag, size, enc)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPart indicates an expected call of RecordPart.
func (mr *MockMetadataStoreMockRecorder) RecordPart(ctx, uploadID, partNumber, etag, size, enc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPart", reflect.TypeOf((*MockMetadataStore)(nil).RecordPart), ctx, uploadID, partNumber, etag, size, enc)
}

// RecordReplica mocks base method.
func (m *MockMetadataStore) RecordReplica(ctx context.Context, key, targetBackend, sourceBackend string, size int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordReplica", ctx, key, targetBackend, sourceBackend, size)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordReplica indicates an expected call of RecordReplica.
func (mr *MockMetadataStoreMockRecorder) RecordReplica(ctx, key, targetBackend, sourceBackend, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordReplica", reflect.TypeOf((*MockMetadataStore)(nil).RecordReplica), ctx, key, targetBackend, sourceBackend, size)
}

// RemoveExcessCopy mocks base method.
func (m *MockMetadataStore) RemoveExcessCopy(ctx context.Context, key, backendName string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveExcessCopy", ctx, key, backendName, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveExcessCopy indicates an expected call of RemoveExcessCopy.
func (mr *MockMetadataStoreMockRecorder) RemoveExcessCopy(ctx, key, backendName, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveExcessCopy", reflect.TypeOf((*MockMetadataStore)(nil).RemoveExcessCopy), ctx, key, backendName, size)
}

// RetryCleanupItem mocks base method.
func (m *MockMetadataStore) RetryCleanupItem(ctx context.Context, id int64, backoff time.Duration, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryCleanupItem", ctx, id, backoff, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryCleanupItem indicates an expected call of RetryCleanupItem.
func (mr *MockMetadataStoreMockRecorder) RetryCleanupItem(ctx, id, backoff, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryCleanupItem", reflect.TypeOf((*MockMetadataStore)(nil).RetryCleanupItem), ctx, id, backoff, lastError)
}

// WithAdvisoryLock mocks base method.
func (m *MockMetadataStore) WithAdvisoryLock(ctx context.Context, lockID int64, fn func(context.Context) error) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithAdvisoryLock", ctx, lockID, fn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithAdvisoryLock indicates an expected call of WithAdvisoryLock.
func (mr *MockMetadataStoreMockRecorder) WithAdvisoryLock(ctx, lockID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithAdvisoryLock", reflect.TypeOf((*MockMetadataStore)(nil).WithAdvisoryLock), ctx, lockID, fn)
}
