// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingCleanups = `-- name: CountPendingCleanups :one
SELECT COUNT(*) FROM cleanup_queue WHERE attempts < 10
`

func (q *Queries) CountPendingCleanups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCleanups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCleanupItem = `-- name: DeleteCleanupItem :exec
DELETE FROM cleanup_queue WHERE id = $1
`

func (q *Queries) DeleteCleanupItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCleanupItem, id)
	return err
}

const deleteCleanupQueueByBackend = `-- name: DeleteCleanupQueueByBackend :exec
DELETE FROM cleanup_queue WHERE backend_name = $1
`

func (q *Queries) DeleteCleanupQueueByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteCleanupQueueByBackend, backendName)
	return err
}

const deleteCleanupQueueByKey = `-- name: DeleteCleanupQueueByKey :execrows
DELETE FROM cleanup_queue
WHERE object_key = $1 AND backend_name = $2
`

type DeleteCleanupQueueByKeyParams struct {
	ObjectKey   string
	BackendName string
}

// Removes every cleanup_queue row matching the given (object_key,
// backend_name) pair. Returns the number of rows deleted so the caller
// can confirm the sum-then-delete pair stayed consistent.
func (q *Queries) DeleteCleanupQueueByKey(ctx context.Context, arg DeleteCleanupQueueByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCleanupQueueByKey, arg.ObjectKey, arg.BackendName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueCleanup = `-- name: EnqueueCleanup :exec
INSERT INTO cleanup_queue (backend_name, object_key, reason, size_bytes)
VALUES ($1, $2, $3, $4)
`

type EnqueueCleanupParams struct {
	BackendName string
	ObjectKey   string
	Reason      string
	SizeBytes   int64
}

func (q *Queries) EnqueueCleanup(ctx context.Context, arg EnqueueCleanupParams) error {
	_, err := q.db.Exec(ctx, enqueueCleanup,
		arg.BackendName,
		arg.ObjectKey,
		arg.Reason,
		arg.SizeBytes,
	)
	return err
}

const getPendingCleanups = `-- name: GetPendingCleanups :many
SELECT id, backend_name, object_key, reason, attempts, size_bytes
FROM cleanup_queue
WHERE next_retry <= NOW() AND attempts < 10
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingCleanupsRow struct {
	ID          int64
	BackendName string
	ObjectKey   string
	Reason      string
	Attempts    int32
	SizeBytes   int64
}

func (q *Queries) GetPendingCleanups(ctx context.Context, limit int32) ([]GetPendingCleanupsRow, error) {
	rows, err := q.db.Query(ctx, getPendingCleanups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingCleanupsRow{}
	for rows.Next() {
		var i GetPendingCleanupsRow
		if err := rows.Scan(
			&i.ID,
			&i.BackendName,
			&i.ObjectKey,
			&i.Reason,
			&i.Attempts,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCleanupQueueSizeByKey = `-- name: SumCleanupQueueSizeByKey :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes,
       COUNT(*)::bigint AS row_count
FROM cleanup_queue
WHERE object_key = $1 AND backend_name = $2
`

type SumCleanupQueueSizeByKeyParams struct {
	ObjectKey   string
	BackendName string
}

type SumCleanupQueueSizeByKeyRow struct {
	TotalBytes int64
	RowCount   int64
}

// Returns the sum of size_bytes for every cleanup_queue row matching the
// given (object_key, backend_name) pair. Used by the reconciler-driven
// sweep so orphan_bytes can be decremented in step with the row delete.
func (q *Queries) SumCleanupQueueSizeByKey(ctx context.Context, arg SumCleanupQueueSizeByKeyParams) (SumCleanupQueueSizeByKeyRow, error) {
	row := q.db.QueryRow(ctx, sumCleanupQueueSizeByKey, arg.ObjectKey, arg.BackendName)
	var i SumCleanupQueueSizeByKeyRow
	err := row.Scan(&i.TotalBytes, &i.RowCount)
	return i, err
}

const updateCleanupRetry = `-- name: UpdateCleanupRetry :exec
UPDATE cleanup_queue
SET attempts = attempts + 1,
    next_retry = NOW() + $1::interval,
    last_error = $2
WHERE id = $3
`

type UpdateCleanupRetryParams struct {
	Backoff   pgtype.Interval
	LastError *string
	ID        int64
}

func (q *Queries) UpdateCleanupRetry(ctx context.Context, arg UpdateCleanupRetryParams) error {
	_, err := q.db.Exec(ctx, updateCleanupRetry, arg.Backoff, arg.LastError, arg.ID)
	return err
}
