// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: multipart.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMultipartUpload = `-- name: CreateMultipartUpload :exec
INSERT INTO multipart_uploads (upload_id, object_key, backend_name, content_type, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type CreateMultipartUploadParams struct {
	UploadID    string
	ObjectKey   string
	BackendName string
	ContentType *string
	Metadata    []byte
}

func (q *Queries) CreateMultipartUpload(ctx context.Context, arg CreateMultipartUploadParams) error {
	_, err := q.db.Exec(ctx, createMultipartUpload,
		arg.UploadID,
		arg.ObjectKey,
		arg.BackendName,
		arg.ContentType,
		arg.Metadata,
	)
	return err
}

const deleteMultipartUpload = `-- name: DeleteMultipartUpload :exec
DELETE FROM multipart_uploads
WHERE upload_id = $1
`

func (q *Queries) DeleteMultipartUpload(ctx context.Context, uploadID string) error {
	_, err := q.db.Exec(ctx, deleteMultipartUpload, uploadID)
	return err
}

const deleteMultipartUploadsByBackend = `-- name: DeleteMultipartUploadsByBackend :exec
DELETE FROM multipart_uploads WHERE backend_name = $1
`

func (q *Queries) DeleteMultipartUploadsByBackend(ctx context.Context, backendName string) error {
	_, err := q.db.Exec(ctx, deleteMultipartUploadsByBackend, backendName)
	return err
}

const getMultipartUpload = `-- name: GetMultipartUpload :one
SELECT upload_id, object_key, backend_name, content_type, metadata, created_at
FROM multipart_uploads
WHERE upload_id = $1
`

type GetMultipartUploadRow struct {
	UploadID    string
	ObjectKey   string
	BackendName string
	ContentType *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetMultipartUpload(ctx context.Context, uploadID string) (GetMultipartUploadRow, error) {
	row := q.db.QueryRow(ctx, getMultipartUpload, uploadID)
	var i GetMultipartUploadRow
	err := row.Scan(
		&i.UploadID,
		&i.ObjectKey,
		&i.BackendName,
		&i.ContentType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getMultipartUploadsByBackend = `-- name: GetMultipartUploadsByBackend :many
SELECT upload_id, object_key, backend_name, content_type, metadata, created_at
FROM multipart_uploads
WHERE backend_name = $1
`

type GetMultipartUploadsByBackendRow struct {
	UploadID    string
	ObjectKey   string
	BackendName string
	ContentType *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetMultipartUploadsByBackend(ctx context.Context, backendName string) ([]GetMultipartUploadsByBackendRow, error) {
	rows, err := q.db.Query(ctx, getMultipartUploadsByBackend, backendName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMultipartUploadsByBackendRow{}
	for rows.Next() {
		var i GetMultipartUploadsByBackendRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.BackendName,
			&i.ContentType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParts = `-- name: GetParts :many
SELECT part_number, etag, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at
FROM multipart_parts
WHERE upload_id = $1
ORDER BY part_number
`

type GetPartsRow struct {
	PartNumber    int32
	Etag          string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetParts(ctx context.Context, uploadID string) ([]GetPartsRow, error) {
	rows, err := q.db.Query(ctx, getParts, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPartsRow{}
	for rows.Next() {
		var i GetPartsRow
		if err := rows.Scan(
			&i.PartNumber,
			&i.Etag,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncryptionKey,
			&i.KeyID,
			&i.PlaintextSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleMultipartUploads = `-- name: GetStaleMultipartUploads :many
SELECT upload_id, object_key, backend_name, content_type, metadata, created_at
FROM multipart_uploads
WHERE created_at < $1
`

type GetStaleMultipartUploadsRow struct {
	UploadID    string
	ObjectKey   string
	BackendName string
	ContentType *string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetStaleMultipartUploads(ctx context.Context, createdAt pgtype.Timestamptz) ([]GetStaleMultipartUploadsRow, error) {
	rows, err := q.db.Query(ctx, getStaleMultipartUploads, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleMultipartUploadsRow{}
	for rows.Next() {
		var i GetStaleMultipartUploadsRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.BackendName,
			&i.ContentType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMultipartUploadsByPrefix = `-- name: ListMultipartUploadsByPrefix :many
SELECT upload_id, object_key, content_type, created_at
FROM multipart_uploads
WHERE object_key LIKE $1 || '%' ESCAPE '\'
ORDER BY object_key, created_at
LIMIT $2
`

type ListMultipartUploadsByPrefixParams struct {
	Prefix     *string
	MaxUploads int32
}

type ListMultipartUploadsByPrefixRow struct {
	UploadID    string
	ObjectKey   string
	ContentType *string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListMultipartUploadsByPrefix(ctx context.Context, arg ListMultipartUploadsByPrefixParams) ([]ListMultipartUploadsByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listMultipartUploadsByPrefix, arg.Prefix, arg.MaxUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMultipartUploadsByPrefixRow{}
	for rows.Next() {
		var i ListMultipartUploadsByPrefixRow
		if err := rows.Scan(
			&i.UploadID,
			&i.ObjectKey,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPart = `-- name: UpsertPart :exec
INSERT INTO multipart_parts (upload_id, part_number, etag, size_bytes, encrypted, encryption_key, key_id, plaintext_size, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (upload_id, part_number) DO UPDATE SET
    etag = $3, size_bytes = $4, encrypted = $5, encryption_key = $6, key_id = $7, plaintext_size = $8, created_at = NOW()
`

type UpsertPartParams struct {
	UploadID      string
	PartNumber    int32
	Etag          string
	SizeBytes     int64
	Encrypted     bool
	EncryptionKey []byte
	KeyID         *string
	PlaintextSize *int64
}

func (q *Queries) UpsertPart(ctx context.Context, arg UpsertPartParams) error {
	_, err := q.db.Exec(ctx, upsertPart,
		arg.UploadID,
		arg.PartNumber,
		arg.Etag,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncryptionKey,
		arg.KeyID,
		arg.PlaintextSize,
	)
	return err
}
